<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gtree [ 
<!ELEMENT gtree (node+)>
<!ELEMENT node (name | user_name? | dist_to_parent? | is_subfamily? |
creation_cost? | subtree_weight? | cutoffs? | children? | affinity_vector? |
tre_vector? | pwid_vector? | weighted_counts? | profiles? |
log_odds_vector? | sam_hmm? | alignment?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user_name (#PCDATA)>
<!ELEMENT dist_to_parent (#PCDATA)>
<!ELEMENT is_subfamily (#PCDATA)>
<!ELEMENT creation_cost (#PCDATA)>
<!ELEMENT subtree_weight (#PCDATA)>
<!ELEMENT cutoffs (#PCDATA)>
<!ELEMENT affinity_vector (#PCDATA)>
<!ELEMENT tre_vector (#PCDATA)>
<!ELEMENT pwid_vector (#PCDATA)>
<!ELEMENT weighted_counts (#PCDATA)>
<!ELEMENT profiles (#PCDATA)>
<!ELEMENT log_odds_vector (#PCDATA)>
<!ELEMENT sam_hmm (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT consensus (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT children ((node | noderef)*)>
]>

<gtree>
  <node>
  <name>N436</name>
  <user_name>N436</user_name>
  <dist_to_parent>0</dist_to_parent>
  <is_subfamily>0</is_subfamily>
  <creation_cost>0.823378</creation_cost>
  <subtree_weight>3</subtree_weight>
  <consensus>MRRGSVAGPGGFGPRPAAdTKETSKKlLAkekYraLTRDLdWEtSYQpmDkvFPeEFdkFEGIKItDWDKWEDPFRLTMDAYWKYQAEKEKKLYAIfDAFAQNNqlNVsDARYvNALKLFLTGVTPLEYQAhrGyAHVGRhFrGaGARVACQMQSIDELRHaQTQAiHtmSHYNKyFnGfhdfrHMHDRVWYLSVPKSFFEDArSAGDPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEViKFLLEQHEDNIvQkWIDKWFWRGyRLLtLVSGMMMDYMLPLEkRVMSWkEAWEvYFEQAGGALFKDYGIRMPKYhevavKEKdHiSHqAWwiFYNYghAAaFHTWiPmtddEMdWLSEKYPDFDrTFDkyYRPrwEhwRagkaERFYNptLPMLCQtCQIPMvFTefTEPDDPTqicyReseYeGErYHFCSDGCkDIFedEPEKYvQAWLPVHQIlQGNCGGadLEdVLkWYnlnPGaDNlDyeGsAWaqawaAgaaGaRAARQ</consensus>
  <cutoffs> 2.5 </cutoffs>
  <children>
    <node>
    <name>N433</name>
    <user_name>N433</user_name>
    <dist_to_parent>0.823378</dist_to_parent>
    <is_subfamily>1</is_subfamily>
    <creation_cost>0.280238</creation_cost>
    <subtree_weight>1.86161</subtree_weight>
    <consensus>MRRGSVAGPGGFGPRPWGNTKEASMAlLnRaDWYDiARTTNWTPSYVtEsELFPEemSGaqGIPMEaWEtYDEPYKtSYPEYVsIQREKDAGAYSVKAALERSkmfEkADPGWkSilKaHYGAIalgEYAAstaEARMARFgRAPGmRNMATFGMLDEnRHGQLQLYFPHdlckKDRQFDWAHKAyHTNEWaAIAARsfFDDifMaRDAIsiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQiGGPaLQILIENGrKeeAQKLVDiAFWRAWRLFSlLTGpSMDYYTPLEHRkmSFKEFMlEWIVgQFERqLiDLGLDKPWYWDqFlneLDyqHHAyHlGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkcWDVIIDNLlaGkiELTvPETLPIVCNMsQLPIcavPGytnGwiwndaPlqLeYNGRLYHFgSEiDRWvFqQDPERYagHlnLVDRFLAGqIQPpDLgGALqYMgLaPGEmGDDAHgYAWVeAaaaaATGARAARR</consensus>
    <children>
      <node>
      <name>N424</name>
      <user_name>N424</user_name>
      <dist_to_parent>0.280238</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.214763</creation_cost>
      <subtree_weight>1.16121</subtree_weight>
      <consensus>------------------------MALLNRDDWYDiaRdlDWdLSYVDpaeAFPaeWkGagDicgeAWDdWDEPFRVSfRdYVmiQRdKEagVgAireAlVRagaYEKLDdaHkAaSHLHMGTicMVEHMAVTMQSRFcRFAPsaRWRnLGaFGMLDETRHTQLDLRFSHDLLkddPrFDWSQkAFHTdEWaVLAtkNfFDDaMLNADCVEAALATSLTlEHGFTNiQFVALAaDAMaAGDiNfSNLLSSIQTDEARHAQlGFPTLdilMeHDPaRAaQiaLDiAFWRStRiFQalTGpaMDYYTPlakRkMSFKEFMLEWIVkHHERILeDYGLkKPWYWDqFeksLdHGHHAlHiGTWFWRPTLFWdPNaGVSkdEReWLneKYPnWEEnWGglWDEIIkNiNadnIEKTLPaTfPmLCNlTnLPiGSafD----SlfdLadeqLtYkGRLYhFDSaiSKWcFElDPERYAGHqNiiDRfIdGQIqPadiaGgLnwMGLTPEVMGeDVfNYaWAK--------------</consensus>
      <children>
        <node>
        <name>UniRef100_A0A0D8HMT3</name>
        <user_name>UniRef100_A0A0D8HMT3</user_name>
        <dist_to_parent>0.214763</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>---------------------------LNRDDWYDTSRNLDWDLSYVDPSEAFPASWSGAGDVPTEAWDKWDEPFRVSYRDYVRIQREKESGVKAVSNALVRSGTYEKLDPAHVAASHLHMGTTCMVEHMAVTMQSRFCRFAPTPRWRNLGVFGMLDETRHTQLDLRFSHDLLKQDPRFDWSQKAFHTNEWGVLAVKNFFDDAMLNADCVEAALATSLTVEHGFTNVQFVALAADAMAAGDINWSNLLSSIQTDEARHAQQGFPTLSILMEHDPAR-AQKALDIAFWRSTRLFQTLTGPAMDYYTPLDQRKMSFKEFMLEWIVNHHERILEDYGLKKPWYWDQFMYSLEHGHHAMHLGTWFWRPTLFWKPNAGVSKDEREWLREKYPTWEENWGGMWDEIIKNVNTDQIEKTLPATFPSLCNLTQLPLGSAF-----SLNDLADHSLTYNGRLYHFDSAISKWCFEQDPERYAGHQNIIDRVIDGQIVPADLAGGLSYMGLTPEVMGEDVYNYAWAK--------------</sequence>
        </node>
        <node>
        <name>UniRef100_O87082</name>
        <user_name>UniRef100_O87082</user_name>
        <dist_to_parent>0.214763</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>------------------------MALLNRDDWYDIARDVDWTLSYVDRAVAFPEEWKGEKDICGTAWDDWDEPFRVSFREYVMVQRDKEASVGAIREAMVRAKAYEKLDDGHKATSHLHMGTITMVEHMAVTMQSRFVRFAPSARWRSLGAFGMLDETRHTQLDLRFSHDLLNDSPSFDWSQRAFHTDEWAVLATRNLFDDIMLNADCVEAALATSLTLEHGFTNIQFVALASDAMEAGDVNFSNLLSSIQTDEARHAQLGFPTLDVMMKHDPKRAQQIL-DVAFWRSYRIFQAVTGVSMDYYTPVAKRQMSFKEFMLEWIVKHHERILRDYGLQKPWYWDTFEKTLDHGHHALHIGTWFWRPTLFWDPNGGVSREERRWLNQKYPNWEESWGVLWDEIISNINAGNIEKTLPETLPMLCNVTNLPIGSHWD-----RFHLKPEQLVYKGRLYTFDSDVSKWIFELDPERYAGHTNVVDRFIGGQIQPMTIEGVLNWMGLTPEVMGKDVFNYRWA---------------</sequence>
        </node>
      </children>
      </node>
      <node>
      <name>N427</name>
      <user_name>N427</user_name>
      <dist_to_parent>0.280238</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.242381</creation_cost>
      <subtree_weight>1.60308</subtree_weight>
      <consensus>MRRGSVAGPGGFGPRPWGNTKEASMAlLeRaDWYDlARTTNWTPsYVTEsELFPEeMSGaqGIPMEkWEtYDEPYKtTYPEYVsIQREKDAGAYSVKAALERSrmFEdADPGWkSiLKAHYGAIALGEYAAssAEARMARFGRAPGmRNMATFGMLDEnRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDiFMaRDAISiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQIGGPALQILIENGrKEEAQKLVDiAIWRAWRLFSLLTGpSMDYYTPLEHRkqSFKEFMtEWIVgQFERqLiDLGLDkPWYWDqFlnELDyQHHAYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTFGKcWDVIIDNLlaGkpELTvPETLPIVCNMSQLPICaVPGytnGwiwndyPldleYNGRlYHFgSEiDRWVFQQDPERYadHltLVDRFLAGqIQPPDLgGALqYMgLAPGEcGDDAHgYAWVEAaaaaATGARAARR</consensus>
      <children>
        <node>
        <name>N415</name>
        <user_name>N415</user_name>
        <dist_to_parent>0.242381</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.163033</creation_cost>
        <subtree_weight>1.5758</subtree_weight>
        <consensus>------------------------MALLeRaDWYDiARTTNWTPsYVTEsELFPeeMsGAqGIPMEkWEtYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdYCaKDRQFDWAHKAYHTNEWAAIAARSFFDDifMsRDAIsVAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIENGRKEEAQKkVDIAIWRAWRLFSlLTGPsMDYYTPLEHRKQSFKEFMtEWIVGQFERtLIDLGLDKPWYWDQFinefDyQHHaYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkCWDVIIDNLLaGkpELTVPETLPIVCNMSQLPICAVPGytNGWiWndydldLEYNGRLYHFGSEiDRWVFQQDPeRYrdHlTLVDRFLAGqIQPmDLgGALkYMnLAPGEcGDDAHdYAWVEA-------------</consensus>
        <children>
          <node>
          <name>N356</name>
          <user_name>N356</user_name>
          <dist_to_parent>0.163033</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.0407674</creation_cost>
          <subtree_weight>1.10746</subtree_weight>
          <consensus>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYKYNGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEA-------------</consensus>
          <children>
            <node>
            <name>UniRef100_Q46PB0</name>
            <user_name>UniRef100_Q46PB0</user_name>
            <dist_to_parent>0.0407674</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>------------------------MALLERAAWYDIARTTNWTPTYVAESDLFPEVMAGAQGVPMEIWETYDEPYKTSYPEYVRIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCPKDRQFDWAHKAYHTNQWGAIAARSTFDDLFMSRSAIEIAVMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIANGRKEQAQQLVDVAIARAWRLFSLLTGTSMDYATPLQHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTVWWNPAAGMTPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGRKELTVPETLPIVCNMSQLPICAVPG--NGWNVRDYPLE--YNGRTYHFNSEIDRWVFQQDPVRYRDHLTLVDRFLAGHIQPPDLGGALRYMNLAPGEIGDDAHQYAWVEA-------------</sequence>
            </node>
            <node>
            <name>N267</name>
            <user_name>N267</user_name>
            <dist_to_parent>0.0407674</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.00183689</creation_cost>
            <subtree_weight>1.05567</subtree_weight>
            <consensus>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYaWVEA-------------</consensus>
            <children>
              <node>
              <name>UniRef100_Q9EZP0</name>
              <user_name>UniRef100_Q9EZP0</user_name>
              <dist_to_parent>0.00183689</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYPWVEA-------------</sequence>
              </node>
              <node>
              <name>UniRef100_Q51939</name>
              <user_name>UniRef100_Q51939</user_name>
              <dist_to_parent>0.00183689</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEA-------------</sequence>
              </node>
            </children>
            </node>
          </children>
          </node>
          <node>
          <name>N414</name>
          <user_name>N414</user_name>
          <dist_to_parent>0.163033</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.169324</creation_cost>
          <subtree_weight>1.37418</subtree_weight>
          <consensus>------------------------MamLnReDWYDLaRTTNWTPkYVTEdeLFPeemSGafdIPMEKWEaYDEPYKqTYPEYVsiQREKDaGAYSVKAALERskiyEnADPGWiStlKlHfGAIalgEYAAsTaEaRMaRFaKAPGnRNMATfGmMDEiRHGQiQLYFPHEhVkKDRQFDWAhKAyHTNEWAAIAARHFFDDIMMtRDAISVgIMLTFgFETGFTNMQFLGLAADAAEAGDhTFASLISSIQTDESRHAQiGGPaLQILIENGkKeEAQKKVDiAfWRAWRLFSVLTGPiMDYYTPLEhRnQSFKEFMlEWIVaQFERsLhDLGLDKPWYWDiFLqdLDeqHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNdTWGqCWDVIidNLVnGrmeLTlPETLPiVCNMcnLPIagtPgytPGdaWNVkDYqLEYNGRLYHFGSEpDRWcFeQdPERYagHMnLVDRFLAGlIQPMDLgGALkYMdLaPGEmGDDAHdYaWVea-------------</consensus>
          <children>
            <node>
            <name>UniRef100_Q00456</name>
            <user_name>UniRef100_Q00456</user_name>
            <dist_to_parent>0.169324</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>------------------------MAMHPRKDWYELTRATNWTPSYVTEEQLFPERMSGHMGIPLEKWESYDEPYKTSYPEYVSIQREKDAGAYSVKAALERAKIYENSDPGWISTLKSHYGAIAVGEYAAVTGEGRMARFSKAPGNRNMATFGMMDELRHGQLQLFFPHEYCKKDRQFDWAWRAYHSNEWAAIAAKHFFDDIITGRDAISVAIMLTFSFETGFTNMQFLGLAADAAEAGDYTFANLISSIQTDESRHAQQGGPALQLLIENGKREEAQKKVDMAIWRAWRLFAVLTGPVMDYYTPLEDRSQSFKEFMYEWIIGQFERSLIDLGLDKPWYWDLFLKDIDELHHSYHMGVWYWRTTAWWNPAAGVTPEERDWLEEKYPGWNKRWGRCWDVITENVLNDRMDLVSPETLPSVCNMSQIPLVGVPGDD----WNIEVFSLEHNGRLYHFGSEVDRWVFQQDPVQYQNHMNIVDRFLAGQIQPMTLEGALKYMGFSIEEMGKDAHDFAWAD--------------</sequence>
            </node>
            <node>
            <name>N413</name>
            <user_name>N413</user_name>
            <dist_to_parent>0.169324</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.173026</creation_cost>
            <subtree_weight>1.24909</subtree_weight>
            <consensus>------------------------MalLNReDWYDLARTTNWTPKYVTEdELFPaElSGafDIPMEKWEaYDEPYKQTYPEYVkVQREKDSGAYSVKAALERSgffEkADPGWkSVMKLHFGAIaLaEYAASTAEARMaRFAKAPGcRNMATfGSMDEIRHGQIQLYFPHEHVSKDRQFDWAHKAfHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPaLQILIENGkKaEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMlEWIVaQFERaLhDLGLDKPWYWDiFLQQLDQQHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNDTWGQCWDVIIDNLVdGkpELTlPETLPIVCNMCNLPIAHTPNYTPGdaWNVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMnLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHdYaWVEa-------------</consensus>
            <children>
              <node>
              <name>UniRef100_O87798</name>
              <user_name>UniRef100_O87798</user_name>
              <dist_to_parent>0.173026</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MSMLKREDWYDLTRTTNWTPKYVTENELFPEEMSGARGISMEAWEKYDEPYKITYPEYVSIQREKDSGAYSIKAALERDGFVDRADPGWVSTMQLHFGAIALEEYAASTAEARMARFAKAPGNRNMATFGMMDENRHGQIQLYFPYANVKRSRKWDWAHKAIHTNEWAAIAARSFFDDMMMTRDSVAVSIMLTFAFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQQGGPSLKILVENGKKDEAQQMVDVAIWRSWKLFSVLTGPIMDYYTPLESRNQSFKEFMLEWIVAQFERQLLDLGLDKPWYWDQFMQDLDETHHGMHLGVWYWRPTVWWDPAAGVSPEEREWLEEKYPGWNDTWGQCWDVITDNLVNGKPELTVPETLPTICNMCNLPIAHTPGNK----WNVKDYQLEYEGRLYHFGSEADRWCFQIDPERYKNHTNLVDRFLKGEIQPADLAGALMYMSLEPGVMGDDAHDYEWVKA-------------</sequence>
              </node>
              <node>
              <name>N411</name>
              <user_name>N411</user_name>
              <dist_to_parent>0.173026</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.153393</creation_cost>
              <subtree_weight>1.12834</subtree_weight>
              <consensus>------------------------MalLNrtDWYDlARTTNcsPeirhedelfpaelegrfDIPMEKWEaYDEPYKQTYPEYVkVQREKDaGaYSVKAALERSkifEkADPGWkSVlKlHfGAIplaEYAAafaeaRleRcakapGcaNMATlGSlDEIRHaQiQLYFPHEHVSKDRQFDWAaKAfdTNEWAAIAaRHFFDDIMMaRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDfTFaSLISSIQTDESRHAQIGGPaLQIfIENGqKaEAQKKVDIAFWRAWRLFSiLTGPiMDYYTPLEHRkQSFKEFMnEWIVeQFERaihDLGLDKPWYWDiFLeQLDQQHHGMHLGVWfWRPTVWWNPaAGVTPaERDWLEEKYPGWNdTWGhCWDVIIdNLVdGntalTlPETLPIVCNMcnLPI----NYTPGdaWaVkDYqLEYNGRLYHFGSEPDRWcFEQEPERYAGHMsLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHgYaWVEV-------------</consensus>
              <children>
                <node>
                <name>UniRef100_O07068</name>
                <user_name>UniRef100_O07068</user_name>
                <dist_to_parent>0.153393</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>------------------------MVLLNSVDWYDLARTTNCSPEIRHRKRTISASVERRVDIPMEKWEGYDEPYKQTYPEYVRVQREKDSGAYSVKAALERSQIYEKADPGWKSVMKQHYGAISLAEY-AAFQRLRLERCARLQGCANMATMGSLDEIRHGQIQLYFPHEHVSKDRQFDWAAKAYHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPALQIFIENGQKAEAQKKVDIAFWRAWRLFSILTGPVMDYYTPLEHRKQSFKEFMNEWIVVQFERALTDLGLDKPWYWDTFLQQLDQQHHGMHLGVWFWRPTVWWNPAAGVTPAERDWLEEKYPGWNSTWGQCWDVIIENLVDGNVAQTYPETLPIVCNMSQLPI----NYTPGDAWAVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMSLVDRFLAGLIQPMDLGGALKYMDLAPGEIGDDAHNYAWVE--------------</sequence>
                </node>
                <node>
                <name>UniRef100_P95408</name>
                <user_name>UniRef100_P95408</user_name>
                <dist_to_parent>0.153393</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>------------------------MAVLNRTDWYDVARTTNWTPKYVTEDELFPPELSGSFDIPMEKWEAYDEPYKQTYPEYVKVQREKDAGVYSVKAALERSKMFENADPGWQSVLKLHFGAIPSGEYAASTAEARMMRFSKAPGMRNMATLGSMDEIRHAQLQLYFPHEHVSKDRQFDWAHKAFDTNEWAAIASRHFFDDIMMARDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDFTFSSLISSIQTDESRHAQIGGPTLQILIENGRKEEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMQEWIVEQFERSIHDLGLDKPWYWDIFLEQLDQQHHGMHLGVWYWRPTVWWNPTAGVTPEERDWLEEKYPGWNDTWGHCWDVIIDNLVEGRTELTLPETLPIVCNMCNLPI----NYTPGNGWNVQDYSLEYNGRLYHFGSEPDRWIFEQEPERYAGHMTLVDRFLAGLIQPMDLGGALAYMDLAPGESGDDAHGYSWVEV-------------</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
          </children>
          </node>
        </children>
        </node>
        <node>
        <name>N426</name>
        <user_name>N426</user_name>
        <dist_to_parent>0.242381</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.254483</creation_cost>
        <subtree_weight>1.11735</subtree_weight>
        <consensus>MRRGSVAGPGGFGPRPWGNTKEASMPKLaRrDwYDlARDmNWaFgYVSEddVFPEELSgsfgihaEeWlaWDEPYKiTYREYVHNQagKDdgiYSiknaIARSaLfdkLDaGWKSaIkAHYGAIpmPEYfASIGEARMaRFGRAAAWRNmAaFGTLDEcRHGQaQafFPYcLiGKdPqaDWAhKAfHTNdWgViAaRqLFDDMFtANDAlSiAiQLTFTfETGFTNLQFLGMAaDAihVGDiEFGaLISSIQTDEARHaQQGEPTiKIlaegGhKaeaQfLiDhMFWRSWklFALLTGiSMDYYTPLEhRTMSFKEFiedWickQFmDQFkDfGlevPWYWEeFlnELdWvHHAiHlGVWfWRPTVWWNPDAGVSAaERdWLEeKYPGWNdrFGKlWDaIGdNiRaGkiEaTfPaTLPiVCNcChiPIcraaGVEAGALagaAPlihTHgGRdllFCcEpCeWifarqPERfagHlSlVDRFLAGeIqPPdLeGaLaYMGisPaeaGnDAqGYAWagAaaaaATGARAARR</consensus>
        <children>
          <node>
          <name>UniRef100_A5ECB8</name>
          <user_name>UniRef100_A5ECB8</user_name>
          <dist_to_parent>0.254483</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>------------------------MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICSPS-------IGQAPRITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASRLAA--------</sequence>
          </node>
          <node>
          <name>UniRef100_Q2JGJ2</name>
          <user_name>UniRef100_Q2JGJ2</user_name>
          <dist_to_parent>0.254483</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>MRRGSVAGPGGFGPRPWGNTKEASMPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGVEAGALASAAPLRHTHGGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQAAAAGATGARAARR</sequence>
          </node>
        </children>
        </node>
      </children>
      </node>
    </children>
    </node>
    <node>
    <name>N435</name>
    <user_name>N435</user_name>
    <dist_to_parent>0.823378</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.301283</creation_cost>
    <subtree_weight>3</subtree_weight>
    <consensus>---------------PAADTKETSKKlLAkekYraLTRDLdWEtSYQpmDkvFPeEFDkFEGIKITDWDKWEDPFRLTMDAYWKYQAEKEKKLYAIfDAFAQNNqlNVsDARYvNALKLFLTGVTPLEYQAHRGYAHVGRhFrGaGARVACQMQSIDELRHvQTQAiHtmSHYNKyFnGfhdfrHMHDRVWYLSVPKSFFEDARSAGGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEVIKFLLEQHEDNIvQkWIDKWFWRGyRLLTLVSGMMMDYMLP--kkVMSWkEAWEvYFEQAGGALFKDYGIRMPKYhevavKEKdHiSHqAWwiFYNYghAAaFHTWiPMtddEMdWLSEKYPDFDrTFDkyYRPrwEhwRageaERFYNptLPMLCQtCQIPMvFTeFTEPDDPTqicyReseYeGERYHFCSDGCkDIFedEPEKYvQAWLPVHQIlQGNCGGadLEdVLrWYninPGaDNlDYeGSAeQQRWaAgaaGgqaAeQ</consensus>
    <children>
      <node>
      <name>N432</name>
      <user_name>N432</user_name>
      <dist_to_parent>0.301283</dist_to_parent>
      <is_subfamily>1</is_subfamily>
      <creation_cost>0.253903</creation_cost>
      <subtree_weight>2.93048</subtree_weight>
      <consensus>---------------PAADmRqAaRPKLSREKYAsMTRDLGWETTYQPMDKVFPhDYDKyEGIKIHDWDKWEDPFRLTMDAYWKYQsEKERKLYAIIDSFqQNNhLNVsDARYlNALKLFLTGVSPLEYAAHRGYAHlGRHFRGVGARVACQMQSIDELRHAQTQTiHTiSHYNKYFnGFheWrHMHDRVWYLSVPKSYFEDAMSAGGPFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFMLEQDpdNIpQKWiDKWFWRGYRLLTLVSAMMMDYMLP--KRVMSWkEAWEiYFEQAGGALFkDYGIRMPKYHEVATKEKDhISHeAWaTFYNYahAAAFHTWVPAkpDEMAWLsEKYPdFDrtYrPRydpWqEqqqAGkgERFYNntLPMLCQTCQIPMVFsaFTEPDDPTqiCYRESeYhGmKYHFCSDGCKDIFDdEPEKYvQAWLPVHQIYQGNCGGAtLpDVLkWYhLnpGaDNlDfEGfaDaQhfAAGAaGaQAaeQ</consensus>
      <children>
        <node>
        <name>N423</name>
        <user_name>N423</user_name>
        <dist_to_parent>0.253903</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.188184</creation_cost>
        <subtree_weight>2.69197</subtree_weight>
        <consensus>---------------PAANQRQAARPKLSREKYAsMTRDLGWETTYQPMDKVFPhDYDKYEGIKIHDWDKWEDPFRLTMDAYWKYQSEKERKLYAIIDSFQQNNqLNVsDARYlNALKLFLTGVSPLEYAAHRGYAHlGRHFRGVGARVAaQMQSIDELRHAQTQTiHTISHYNKYFnGFheWRHMHDRVWYLSVPKSYFEDAMSAGGPFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLLEQDndNIpQKWiDKWFWRGYRLLTLVSAMMMDYMLP--KRVMSWkEAWEmYFEQAGGALFkDYGlRMPKYHEVATKEKDRISHEAWaTFYNYahAAAFHTWvPDkpdEMAWLsEKYPdFDrtYrPRydpWqEqqqAGkgERFYNntLPMLCQTCQIPMVFSaFTEPDDPTqtCYRESeYhGmKYHFCSDGCKDIFDdEPEKYvQAWLPVHQIYQGNCGGATLpDVLkWYhLnpGaDNlDfEGQDRANhfAAGAaGaQAaeQ</consensus>
        <children>
          <node>
          <name>N421</name>
          <user_name>N421</user_name>
          <dist_to_parent>0.188184</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.189044</creation_cost>
          <subtree_weight>2.63012</subtree_weight>
          <consensus>---------------PAANQRQAARPKLSREKYAsMTRDLGWETTYQPMDKVFPhDYDKfEGIKIHDWDKWEDPFRLTMDAYWKYQSEKERKLYAIIDSFQQNNqLNVsDARYlNALKLFLTGVSPLEYAAHRGYAHlGRHFRGVGARVAAQMQSIDELRHAQTQTiHTISHYNKYFnGFhEWRHMHDRVWYLSVPKSYFEDAMSAGGPFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLLEQDpdNIpQKWiDKWFWRGYRLLTLVSAMMMDYMLP--KRVMSWkEAWEmYFEQAGGALFkDYGLRMPKYHEVATKEKDRISHEAWaTFYNYahAAAFHTWvPDkpdEMAWLaEKYPDFDrtYrPRydpWqEqqqAGkgERFYNntLPMLCQTCQIPMVFSaFTEPDDPTQtCYRESeYhGmKYHFCSDGCKDIFDdEPEKYvQAWLPVHQIYQGNCGGATLpDVLkWYhLnpGaDNlDfEGQDRANhfAAGAaGaQAaeQ</consensus>
          <children>
            <node>
            <name>N397</name>
            <user_name>N397</user_name>
            <dist_to_parent>0.189044</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.108566</creation_cost>
            <subtree_weight>1.77225</subtree_weight>
            <consensus>-----------------------------REKYASMTRDLAWETTYEPMDKVFP--FDKYEGIKIHDWDKWEDPFRMTMDAYWKYQSEKERKLYAIIDSVQNNGHLNVSDPRYLNALRLFLTGVTPLEYAAHRGYAHLGRHFRGAGARVAAQMQSIDELRHAQTQ-LHTLSVYNKYFHGFGEWRHMHDRVWYLSVPKSYFEDAMSAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLCEQGNIPILQKWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWAEAWEMYFEQAGGALFKDYGLRMPKYHEVATkTKDRITHEAWGTFYNYAAAAGFHTWVP-KADEMAWLAEKYPQFERYYKPRLDhWqERQQAGQgERFYNATLPMLCQTCQIPMVFS---EPDDPTQTCYRESSYHGMKFHFCSDGCKDIFDDEPAKYAQAWLPVHQIYQGNCGGATLdDVLKWYRLNPGADNLDFEG-------------------</consensus>
            <children>
              <node>
              <name>N363</name>
              <user_name>N363</user_name>
              <dist_to_parent>0.108566</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.0470791</creation_cost>
              <subtree_weight>1.18408</subtree_weight>
              <consensus>-----------------------------------MTRDLGWETSYQPMDKVFP--FDQYEGIKIHDWDKWEDPFRMTMDAYWKYQAEKERKLYAIIDSFAQNNGHMNVDARYINTLKLFLTGVTPLEYAAHRGYAHLGRHFRGVGARVACQMQSIDELRHCQTQ-VHTLSLYNKYFNGFAEWPHMYDRVWYLSVPKSYFEDAMSAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLCEQDPVNIVQKWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWSEAWKIYFEDAGGALFKDYGLRMPKYHEIATQTKDRITHEAWATFYNYGAAADFHTWVP-SDEELDWLSAKYPEFDSVYRPRFEYWREQQQAGK--RFYNANLPMLCQTCQVPMFFS---EPDDPTKIAYRESTYHGMKFHFCSDGCKDIFEGEPEKYVQAWLPVHQIYQGNCGGASLDDVLKYYHLnHGHDNLDFAG-------------------</consensus>
              <children>
                <node>
                <name>UniRef100_A0A1N7SHQ2</name>
                <user_name>UniRef100_A0A1N7SHQ2</user_name>
                <dist_to_parent>0.0470791</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>-----------------------------------MTRDLGWQTTYQPMDEVFP--YDKYEGIVIHDWDKWEDPFRMTMDSYWKYQAEKERKLYAIIDSFAQNNGHMNVDARYINTLKLFLTGVTPLEYSAHRNYAHLGRHFRGVGARVACQMQSIDELRHCQTQ-VHTLSLYNKYFNGFSEWPHMHDRVWYLSVPKSYFEDAATAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFLCEQDPVNIVQRWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWSEAWKIYFEDAGGALFQDYGLRMPKYHEIATQTKDRITHEAWGTFYNYAGAADFHTWVP-SDEELDWLSAKYPEFDRLYRPRLEYWREQQQAGK--RFYNTNLPMLCQTCQIPLTFS---EPDDPTKIAYRESTYHGMKFHFCSDGCKDIFDGEPEKYVQAWLPVHQIYQGNCGGATLDDVLEYYHIRNGHENLDFAG-------------------</sequence>
                </node>
                <node>
                <name>N344</name>
                <user_name>N344</user_name>
                <dist_to_parent>0.0470791</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0.0177253</creation_cost>
                <subtree_weight>1.09926</subtree_weight>
                <consensus>-----------------------------------MTRDLGWETSYQPMDKVFP--FDQYEGIKIHDWDKWEDPFRMTMDAYWKYQAEKERKLYAIIDSFAQNNGHMNVDARYINTLKLFLTGVTPLEYAAHRGYAHLGRHFRGVGARVACQMQSIDELRHCQTQ-VHTLSLYNKYFNGFAEWPHMYDRVWYLSVPKSYFEDAMSAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLCEadndnIVQKWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWSEAWKIYFEDAGGALFKDYGLRMPKYHEIATQTKDRiTHEAWATFYNYGAAADFHTWVP-SDEELDWLSAKYPdFDSVYRPRFEYWREQQQAGK--RFYNAnLPMLCQTCQVPMFFS---EPDDPTKIAYRESTYHGMKFHFCSDGCKDIFEGEPEKYVQAWLPVHQIYQGNCGGASLdDVLKYYhLnHGHDNLDFAG-------------------</consensus>
                <children>
                  <node>
                  <name>UniRef100_A0A2N7VQA1</name>
                  <user_name>UniRef100_A0A2N7VQA1</user_name>
                  <dist_to_parent>0.0177253</dist_to_parent>
                  <is_subfamily>0</is_subfamily>
                  <creation_cost>0</creation_cost>
                  <subtree_weight>1</subtree_weight>
                  <sequence>-----------------------------------MTRDLGWETSYQPMDKVFP--FDQYEGIKIHDWDKWEDPFRMTMDAYWKYQAEKERKLYAIIDSFAQNNGHMNVDARYINTLKLFLTGVTPLEYAAHRGYAHLGRHFRGVGARVACQMQSIDELRHCQTQ-VHTLSLYNKYFNGFAEWPHMYDRVWYLSVPKSYFEDAMSAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLCEAGNVPIVQKWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWSEAWKIYFEDAGGALFKDYGLRMPKYHEIATQTKDRITHEAWATFYNYGAAADFHTWVP-SDEELDWLSAKYPDFDSVYRPRFEYWREQQQAGK--RFYNANLPMLCQTCQVPMFFS---EPDDPTKIAYRESTYHGMKFHFCSDGCKDIFEGEPEKYVQAWLPVHQIYQGNCGGASLEDVLKYYNLSHGHDNLDFAG-------------------</sequence>
                  </node>
                  <node>
                  <name>UniRef100_UPI0003730424</name>
                  <user_name>UniRef100_UPI0003730424</user_name>
                  <dist_to_parent>0.0177253</dist_to_parent>
                  <is_subfamily>0</is_subfamily>
                  <creation_cost>0</creation_cost>
                  <subtree_weight>1</subtree_weight>
                  <sequence>-----------------------------------MTRDLGWETSYQPMDKVFP--FDQYEGIKIHDWDKWEDPFRMTMDAYWKYQAEKERKLYAIIDSFAQNNGHMNVDARYINTLKLFLTGVTPLEYAAHRGYAHLGRHFRGVGARVACQMQSIDELRHCQTQ-VHTLSLYNKYFNGFAEWPHMYDRVWYLSVPKSYFEDAMSAG-PFEFITAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVVKFLCEQDPDNIVQKWLDKWFWRGFRLLTLV-GMMMDYMLP--KRVMSWSEAWKIYFEDAGGALFKDYGLRMPKYHEIATQTKDRVTHEAWATFYNYGAAADFHTWVP-SDEELDWLSAKYPEFDSVYRPRFEYWREQQQAGK--RFYNASLPMLCQTCQVPMFFS---EPDDPTKIAYRESTYHGMKFHFCSDGCKDIFEGEPEKYVQAWLPVHQIYQGNCGGASLDDVLKYYHLNHGHDNLDFAG-------------------</sequence>
                  </node>
                </children>
                </node>
              </children>
              </node>
              <node>
              <name>N367</name>
              <user_name>N367</user_name>
              <dist_to_parent>0.108566</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.051759</creation_cost>
              <subtree_weight>1.68853</subtree_weight>