<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gtree [ 
<!ELEMENT gtree (node+)>
<!ELEMENT node (name | user_name? | dist_to_parent? | is_subfamily? |
creation_cost? | subtree_weight? | cutoffs? | children? | affinity_vector? |
tre_vector? | pwid_vector? | weighted_counts? | profiles? |
log_odds_vector? | sam_hmm? | alignment?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user_name (#PCDATA)>
<!ELEMENT dist_to_parent (#PCDATA)>
<!ELEMENT is_subfamily (#PCDATA)>
<!ELEMENT creation_cost (#PCDATA)>
<!ELEMENT subtree_weight (#PCDATA)>
<!ELEMENT cutoffs (#PCDATA)>
<!ELEMENT affinity_vector (#PCDATA)>
<!ELEMENT tre_vector (#PCDATA)>
<!ELEMENT pwid_vector (#PCDATA)>
<!ELEMENT weighted_counts (#PCDATA)>
<!ELEMENT profiles (#PCDATA)>
<!ELEMENT log_odds_vector (#PCDATA)>
<!ELEMENT sam_hmm (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT consensus (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT children ((node | noderef)*)>
]>

<gtree>
  <node>
  <name>N526</name>
  <user_name>N526</user_name>
  <dist_to_parent>0</dist_to_parent>
  <is_subfamily>0</is_subfamily>
  <creation_cost>0.799034</creation_cost>
  <subtree_weight>3</subtree_weight>
  <consensus>MALLnREKYAsLTRDLdWEtSYQdmddvFPHeYEeFEGIKITDWdKWEDPFRLTMDAYWKYQAEKEKKLYAIFDAFAQNNqlNvSDARYVNALKLFLTGVTPLEYQAyQGYAHVGRQFsGaGARVACQMQSIDELRHVQTQIHAMSHYNKfFdGFDWaHdaMHDRVWYLSVPKSFFEDAfRSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEVIKFLLEQHEDNIVQkWIDKWFWRGyRLLtLVSGMMMDYMLPVMSWkEAWwEyYfEQAGGALFKDLeRYGIRMPKYhEvavkEKehiSHqaWwtFYnyghAAaFHTWiPptdEEMDWLSEKYPDTFDkYYRPrrerwkhwqAekgeRFYNnTLPmLCQvCQIPMffepdDpTtqshRrssYeGERYHFCSDGCkDIFedEPEKYvQAWLPVHQIlQGNCGGaDLEdVLrYYniNpGedgdDAhgspWqerwRnwRgqKPAA</consensus>
  <cutoffs> 2.5 </cutoffs>
  <children>
    <node>
    <name>N523</name>
    <user_name>N523</user_name>
    <dist_to_parent>0.799034</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.282561</creation_cost>
    <subtree_weight>1.91146</subtree_weight>
    <consensus>MALLnRaDWYDiARTTNWTPSYVtEsELFPEemSGaqGIPMEaWEtYDEPYKtSYPEYVsIQREKDAGAYSVKAALERSkmfEkADPGWkSilKaHYGAIalgEYAAstaEARMARFgRAPGmRNMATFGMLDEnRHGQLQLYFPHdlckKDRQFDWAHKAyHTNEWaAIAARsfFDDifMaRDAIsiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQiGGPaLQILIENGrKeeAQKlVDiAFWRAWRLFSlLTGpSMDYYTPLEHRkmSFKEFMlEWIVgQFERqLiDLGLDKPWYWDqFlneLDyqHHAyHlGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkcWDVIIDNLlaGkiELTvPETLPIVCNMsQLPIcavPGnGWnVkDYpLeYNGRLYHFgSEiDRWvFqQDPERYagHlnLVDRFLAGqIQPpDLgGALqYMgLaPGEmGDDAHgYAWVeAYrnqRyQKKAA</consensus>
    <children>
      <node>
      <name>N513</name>
      <user_name>N513</user_name>
      <dist_to_parent>0.282561</dist_to_parent>
      <is_subfamily>1</is_subfamily>
      <creation_cost>0.216903</creation_cost>
      <subtree_weight>1.1155</subtree_weight>
      <consensus>MALLNRDDWYDiaRdlDWdLSYVDpaeAFPaeWkGagDicgeAWDdWDEPFRVSfRdYVmiQRdKEagVgAireAlVRagaYEKLDdaHkAaSHLHMGTicMVEHMAVTMQSRFcRFAPsaRWRnLGaFGMLDETRHTQLDLRFSHDLLkddPrFDWSQkAFHTdEWaVLAtkNfFDDaMLNADCVEAALATSLTlEHGFTNiQFVALAaDAMaAGDiNfSNLLSSIQTDEARHAQlGFPTLdilMeHDPkARAQkaLDiAFWRStRiFQalTGpaMDYYTPlakRkMSFKEFMLEWIVkHHERILeDYGLkKPWYWDqFeksLdHGHHAlHiGTWFWRPTLFWdPNaGVSkdEReWLneKYPnWEEnWGglWDEIIkNiNadnIEKTLPaTfPmLCNlTnLPiGSAfsdndhaKdeqLtYkGRLYhFDSaiSKWcFElDPERYAGHqNiiDRfIdGQIqPadiaGgLnwMGLTPEVMGeDVfNYaWAgDYAENR------</consensus>
      <children>
        <node>
        <name>UniRef100_O87082</name>
        <user_name>UniRef100_O87082</user_name>
        <dist_to_parent>0.216903</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>MALLNRDDWYDIARDVDWTLSYVDRAVAFPEEWKGEKDICGTAWDDWDEPFRVSFREYVMVQRDKEASVGAIREAMVRAKAYEKLDDGHKATSHLHMGTITMVEHMAVTMQSRFVRFAPSARWRSLGAFGMLDETRHTQLDLRFSHDLLNDSPSFDWSQRAFHTDEWAVLATRNLFDDIMLNADCVEAALATSLTLEHGFTNIQFVALASDAMEAGDVNFSNLLSSIQTDEARHAQLGFPTLDVMMKHDPK-RAQQILDVAFWRSYRIFQAVTGVSMDYYTPVAKRQMSFKEFMLEWIVKHHERILRDYGLQKPWYWDTFEKTLDHGHHALHIGTWFWRPTLFWDPNGGVSREERRWLNQKYPNWEESWGVLWDEIISNINAGNIEKTLPETLPMLCNVTNLPIGS-HWDRFHLKPEQLVYKGRLYTFDSDVSKWIFELDPERYAGHTNVVDRFIGGQIQPMTIEGVLNWMGLTPEVMGKDVFNYRWAGDYAENR------</sequence>
        </node>
        <node>
        <name>UniRef100_A0A0D8HMT3</name>
        <user_name>UniRef100_A0A0D8HMT3</user_name>
        <dist_to_parent>0.216903</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>--LLNRDDWYDTSRNLDWDLSYVDPSEAFPASWSGAGDVPTEAWDKWDEPFRVSYRDYVRIQREKESGVKAVSNALVRSGTYEKLDPAHVAASHLHMGTTCMVEHMAVTMQSRFCRFAPTPRWRNLGVFGMLDETRHTQLDLRFSHDLLKQDPRFDWSQKAFHTNEWGVLAVKNFFDDAMLNADCVEAALATSLTVEHGFTNVQFVALAADAMAAGDINWSNLLSSIQTDEARHAQQGFPTLSILMEHD-PARAQKALDIAFWRSTRLFQTLTGPAMDYYTPLDQRKMSFKEFMLEWIVNHHERILEDYGLKKPWYWDQFMYSLEHGHHAMHLGTWFWRPTLFWKPNAGVSKDEREWLREKYPTWEENWGGMWDEIIKNVNTDQIEKTLPATFPSLCNLTQLPLGSAFSLNDLA-DHSLTYNGRLYHFDSAISKWCFEQDPERYAGHQNIIDRVIDGQIVPADLAGGLSYMGLTPEVMGEDVYNYAWAKDY----------</sequence>
        </node>
      </children>
      </node>
      <node>
      <name>N519</name>
      <user_name>N519</user_name>
      <dist_to_parent>0.282561</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.233383</creation_cost>
      <subtree_weight>1.62825</subtree_weight>
      <consensus>MAlLeRaDWYDlARTTNWTPsYVTEsELFPEeMSGaqGIPMEkWEtYDEPYKtTYPEYVsIQREKDAGAYSVKAALERSrmFEdADPGWkSiLKAHYGAIALGEYAAssAEARMARFGRAPGmRNMATFGMLDEnRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDiFMaRDAISiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQIGGPALQILIENGrKEEAQKLVDiAIWRAWRLFSLLTGpSMDYYTPLEHRkqSFKEFMtEWIVgQFERqLiDLGLDkPWYWDqFlnELDyQHHAYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTFGKcWDVIIDNLlaGkpELTvPETLPIVCNMSQLPIcavPGNGWnVkDYpLEYNGRlYHFgSEiDRWVFQQDPERYadHltLVDRFLAGqIQPPDLgGALqYMgLAPGEcGDDAHgYAWVEAYrnqRyQKKAA</consensus>
      <children>
        <node>
        <name>N503</name>
        <user_name>N503</user_name>
        <dist_to_parent>0.233383</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0.162797</creation_cost>
        <subtree_weight>1.39948</subtree_weight>
        <consensus>MALLeRaDWYDiARTTNWTPsYVTEsELFPeeMsGAqGIPMEkWEtYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdYCaKDRQFDWAHKAYHTNEWAAIAARSFFDDifMsRDAIsVAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIENGRKEEAQKkVDIAIWRAWRLFSlLTGPsMDYYTPLEHRKQSFKEFMtEWIVGQFERtLIDLGLDKPWYWDQFinefDyQHHaYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkCWDVIIDNLLaGkpELTVPETLPIVCNMSQLPIcaVPGNGWNVKDYpLEYNGRLYHFGSEiDRWVFQQDPeRYrdHlTLVDRFLAGqIQPmDLgGALkYMnLAPGEcGDDAHdYAWVEAYknqRyQKKAA</consensus>
        <children>
          <node>
          <name>UniRef100_Q00456</name>
          <user_name>UniRef100_Q00456</user_name>
          <dist_to_parent>0.162797</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>MAMHPRKDWYELTRATNWTPSYVTEEQLFPERMSGHMGIPLEKWESYDEPYKTSYPEYVSIQREKDAGAYSVKAALERAKIYENSDPGWISTLKSHYGAIAVGEYAAVTGEGRMARFSKAPGNRNMATFGMMDELRHGQLQLFFPHEYCKKDRQFDWAWRAYHSNEWAAIAAKHFFDDIITGRDAISVAIMLTFSFETGFTNMQFLGLAADAAEAGDYTFANLISSIQTDESRHAQQGGPALQLLIENGKREEAQKKVDMAIWRAWRLFAVLTGPVMDYYTPLEDRSQSFKEFMYEWIIGQFERSLIDLGLDKPWYWDLFLKDIDELHHSYHMGVWYWRTTAWWNPAAGVTPEERDWLEEKYPGWNKRWGRCWDVITENVLNDRMDLVSPETLPSVCNMSQIPLVGVPGDDWNIEVFSLEHNGRLYHFGSEVDRWVFQQDPVQYQNHMNIVDRFLAGQIQPMTLEGALKYMGFSIEEMGKDAHDFAWADKCK---------</sequence>
          </node>
          <node>
          <name>N502</name>
          <user_name>N502</user_name>
          <dist_to_parent>0.162797</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.155665</creation_cost>
          <subtree_weight>1.32823</subtree_weight>
          <consensus>MALLeRaaWYDiARTTNWTPkYVTEsELFPdeMsGAqGiPMEkWEtYDEPYKtsYPEYVsIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDlfMsRdAIdiaIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIaNGRKEeAQKlVDIAIaRAWRLFSlLTGpsMDYaTPLeHRKeSFKEFMtEWIVgQFERtLiDLGLDkPWYWDQfinefDyQHHamhlGiWFWRPTVWWNPAAGvTPdcRDWLEEKYPGWNDTfGkaWDVIIDNLlaGkpELTVPETLPIVCNMSQLPIcatPGNGWnVKDYpLEYnGRlYHFgSEiDRWvFQQDPeRYrdHlTLVDRFLAGlIQPpDLgGALqYMnLAPGEcGDDAHhYaWVEAYrnqRyQKKAA</consensus>
          <children>
            <node>
            <name>N432</name>
            <user_name>N432</user_name>
            <dist_to_parent>0.155665</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.0458436</creation_cost>
            <subtree_weight>1.02591</subtree_weight>
            <consensus>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEAYRNQRYQKKAA</consensus>
            <children>
              <node>
              <name>UniRef100_Q46PB0</name>
              <user_name>UniRef100_Q46PB0</user_name>
              <dist_to_parent>0.0458436</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>MALLERAAWYDIARTTNWTPTYVAESDLFPEVMAGAQGVPMEIWETYDEPYKTSYPEYVRIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCPKDRQFDWAHKAYHTNQWGAIAARSTFDDLFMSRSAIEIAVMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIANGRKEQAQQLVDVAIARAWRLFSLLTGTSMDYATPLQHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTVWWNPAAGMTPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGRKELTVPETLPIVCNMSQLPICAVPGNGWNVRDYPLEYNGRTYHFNSEIDRWVFQQDPVRYRDHLTLVDRFLAGHIQPPDLGGALRYMNLAPGEIGDDAHQYAWVEAYRRQREQNKAA</sequence>
              </node>
              <node>
              <name>N310</name>
              <user_name>N310</user_name>
              <dist_to_parent>0.0458436</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.00179656</creation_cost>
              <subtree_weight>1.00069</subtree_weight>
              <consensus>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYaWVEAYRNQRYQKKAA</consensus>
              <children>
                <node>
                <name>UniRef100_Q51939</name>
                <user_name>UniRef100_Q51939</user_name>
                <dist_to_parent>0.00179656</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEAYRNQRYQKKAA</sequence>
                </node>
                <node>
                <name>UniRef100_Q9EZP0</name>
                <user_name>UniRef100_Q9EZP0</user_name>
                <dist_to_parent>0.00179656</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYPWVEAYRNQRYQKKAA</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
            <node>
            <name>N501</name>
            <user_name>N501</user_name>
            <dist_to_parent>0.155665</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.172955</creation_cost>
            <subtree_weight>1.17962</subtree_weight>
            <consensus>MalLNReDWYDLARTTNWTPKYVTEdELFPaElSGafDIPMEKWEaYDEPYKQTYPEYVkVQREKDSGAYSVKAALERSgffEkADPGWkSVMKLHFGAIaLaEYAASTAEARMaRFAKAPGcRNMATfGSMDEIRHGQIQLYFPHEHVSKDRQFDWAHKAfHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPaLQILIENGkKaEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMlEWIVaQFERaLhDLGLDKPWYWDiFLQQLDQQHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNDTWGQCWDVIIDNLVdGkpELTlPETLPIVCNMCNLPINYTPGNaWNVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMnLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHdYaWVEaYKQkRmkK---</consensus>
            <children>
              <node>
              <name>UniRef100_O87798</name>
              <user_name>UniRef100_O87798</user_name>
              <dist_to_parent>0.172955</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>MSMLKREDWYDLTRTTNWTPKYVTENELFPEEMSGARGISMEAWEKYDEPYKITYPEYVSIQREKDSGAYSIKAALERDGFVDRADPGWVSTMQLHFGAIALEEYAASTAEARMARFAKAPGNRNMATFGMMDENRHGQIQLYFPYANVKRSRKWDWAHKAIHTNEWAAIAARSFFDDMMMTRDSVAVSIMLTFAFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQQGGPSLKILVENGKKDEAQQMVDVAIWRSWKLFSVLTGPIMDYYTPLESRNQSFKEFMLEWIVAQFERQLLDLGLDKPWYWDQFMQDLDETHHGMHLGVWYWRPTVWWDPAAGVSPEEREWLEEKYPGWNDTWGQCWDVITDNLVNGKPELTVPETLPTICNMCNLPIAHTPGNKWNVKDYQLEYEGRLYHFGSEADRWCFQIDPERYKNHTNLVDRFLKGEIQPADLAGALMYMSLEPGVMGDDAHDYEWVKAYQKK-------</sequence>
              </node>
              <node>
              <name>N499</name>
              <user_name>N499</user_name>
              <dist_to_parent>0.172955</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.154339</creation_cost>
              <subtree_weight>1.08056</subtree_weight>
              <consensus>MalLNrtDWYDlARTTNcsPeirhedelfpaelegrfDIPMEKWEaYDEPYKQTYPEYVkVQREKDaGaYSVKAALERSkifEkADPGWkSVlKlHfGAIplaEYAAfqAeaRleRcakapGcaNMATlGSlDEIRHaQiQLYFPHEHVSKDRQFDWAaKAfdTNEWAAIAaRHFFDDIMMaRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDfTFaSLISSIQTDESRHAQIGGPaLQIfIENGqKaEAQKKVDIAFWRAWRLFSiLTGPiMDYYTPLEHRkQSFKEFMnEWIVeQFERaihDLGLDKPWYWDiFLeQLDQQHHGMHLGVWfWRPTVWWNPaAGVTPaERDWLEEKYPGWNdTWGhCWDVIIdNLVdGntalTlPETLPIVCNMcnLPINYTPGdaWaVkDYqLEYNGRLYHFGSEPDRWcFEQEPERYAGHMsLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHgYaWVEiYKQlRmkK---</consensus>
              <children>
                <node>
                <name>UniRef100_O07068</name>
                <user_name>UniRef100_O07068</user_name>
                <dist_to_parent>0.154339</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MVLLNSVDWYDLARTTNCSPEIRHRKRTISASVERRVDIPMEKWEGYDEPYKQTYPEYVRVQREKDSGAYSVKAALERSQIYEKADPGWKSVMKQHYGAISLAEYAAFQ-RLRLERCARLQGCANMATMGSLDEIRHGQIQLYFPHEHVSKDRQFDWAAKAYHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPALQIFIENGQKAEAQKKVDIAFWRAWRLFSILTGPVMDYYTPLEHRKQSFKEFMNEWIVVQFERALTDLGLDKPWYWDTFLQQLDQQHHGMHLGVWFWRPTVWWNPAAGVTPAERDWLEEKYPGWNSTWGQCWDVIIENLVDGNVAQTYPETLPIVCNMSQLPINYTPGDAWAVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMSLVDRFLAGLIQPMDLGGALKYMDLAPGEIGDDAHNYAWVEIYKQMRMNK---</sequence>
                </node>
                <node>
                <name>UniRef100_P95408</name>
                <user_name>UniRef100_P95408</user_name>
                <dist_to_parent>0.154339</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MAVLNRTDWYDVARTTNWTPKYVTEDELFPPELSGSFDIPMEKWEAYDEPYKQTYPEYVKVQREKDAGVYSVKAALERSKMFENADPGWQSVLKLHFGAIPSGEYAASTAEARMMRFSKAPGMRNMATLGSMDEIRHAQLQLYFPHEHVSKDRQFDWAHKAFDTNEWAAIASRHFFDDIMMARDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDFTFSSLISSIQTDESRHAQIGGPTLQILIENGRKEEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMQEWIVEQFERSIHDLGLDKPWYWDIFLEQLDQQHHGMHLGVWYWRPTVWWNPTAGVTPEERDWLEEKYPGWNDTWGHCWDVIIDNLVEGRTELTLPETLPIVCNMCNLPINYTPGNGWNVQDYSLEYNGRLYHFGSEPDRWIFEQEPERYAGHMTLVDRFLAGLIQPMDLGGALAYMDLAPGESGDDAHGYSWVEVYKQLRTKK---</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
          </children>
          </node>
        </children>
        </node>
        <node>
        <name>N518</name>
        <user_name>N518</user_name>
        <dist_to_parent>0.233383</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.254591</creation_cost>
        <subtree_weight>1.13731</subtree_weight>
        <consensus>MPKLaRrDwYDlARDmNWaFgYVSEddVFPEELSgsfgihaEeWlaWDEPYKiTYREYVHNQagKDdgiYSiknaIARSaLfdkLDaGWKSaIkAHYGAIpmPEYfASIGEARMaRFGRAAAWRNmAaFGTLDEcRHGQaQafFPYcLiGKdPqaDWAhKAfHTNdWgViAaRqLFDDMFtANDAlSiAiQLTFTfETGFTNLQFLGMAaDAihVGDiEFGaLISSIQTDEARHaQQGEPTiKIlaegGhKaeaQfLiDhMFWRSWklFALLTGiSMDYYTPLEhRTMSFKEFiedWickQFmDQFkDfGlevPWYWEeFlnELdWvHHAiHlGVWfWRPTVWWNPDAGVSAaERdWLEeKYPGWNdrFGKlWDaIGdNiRaGkiEaTfPaTLPiVCNcChiPIcrAagaGaaarAAilrHnGRdllFCcEpCeWifarqPERfagHlSlVDRFLAGeIqPPdLeGaLaYMGisPaeaGnDAqGYAWagASR---------</consensus>
        <children>
          <node>
          <name>N527</name>
          <user_name>N527</user_name>
          <dist_to_parent>0.254591</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>MPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGAGALASAAPLRHTGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQA-----------</consensus>
          <children>
            <node>
            <name>UniRef100_Q2JGJ2</name>
            <user_name>UniRef100_Q2JGJ2</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>MPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGAGALASAAPLRHTGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQA-----------</sequence>
            </node>
          </children>
          </node>
          <node>
          <name>N528</name>
          <user_name>N528</user_name>
          <dist_to_parent>0.254591</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICS-PSIGQAPR--ITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASR---------</consensus>
          <children>
            <node>
            <name>UniRef100_A5ECB8</name>
            <user_name>UniRef100_A5ECB8</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICS-PSIGQAPR--ITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASR---------</sequence>
            </node>
          </children>
          </node>
        </children>
        </node>
      </children>
      </node>
    </children>
    </node>
    <node>
    <name>N525</name>
    <user_name>N525</user_name>
    <dist_to_parent>0.799034</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.316597</creation_cost>
    <subtree_weight>3</subtree_weight>
    <consensus>--LNQREKYASLTRDLdWEtSYQdmddvFPHIYEeFEGIKITDWDKWEDPFRLTMDAYWKYQAEKEKKLYAIFDAFAQNNqlNVSDARYVNALKLFLTGVTPLEYQAyQGYAHVGRQFsGaGARVACQMQSIDELRHVQTQIHAMSHYNKfFdGFDWaHdhMHDRVWYLSVPKSFFEDAARSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEVIKFLLEQHEDNIVQkWIDKWFWRGyRLLtLVSGMMMDYMLPVMSWkEAWwEyYFEQAGGALFKDLeRYGIRMPKYhEVAvKEKeHiSHqaWwtFYnyghAAaFHTWiPptdEEMDWLSEKYPDTFDkYYRPrrerwkhwqAekgeRFYNnTLPmLCQvCQIPMffepdDPTTqshRrssYeGERYHFCSDGCkDIFedEPEKYvQAWLPVHQIlQGNCGGaDLEdVLrYYniNpGqDNgDaegSPdQdRWRnWrGdkPAA</consensus>
    <children>
      <node>
      <name>N522</name>
      <user_name>N522</user_name>
      <dist_to_parent>0.316597</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.278051</creation_cost>
      <subtree_weight>3</subtree_weight>
      <consensus>--LNQREKYASLTRDLdWEtSYQdmddvFPHIYEeFEGIKITDWDKWEDPFRLTMDAYWKYQAEKEKKLYAIFDAFAQNNqlNVSDARYVNALKLFLTGVTPLEYQAyQGYAHVGRQFsGaGARVACQMQSIDELRHVQTQIHAMSHYNKfFdGFDWaHdhMHDRVWYLSVPKSFFEDAaRSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEVIKFLLEQHEDNIVQkWIDKWFWRGyRLLtLVSGMMMDYMLPVMSWkEAWwEyYFEQAGGALFKDLeRYGIRMPKYhEVAvKEKeHiSHqaWwtFYnyghAAaFHTWiPptdEEMDWLSEKYPDTFDkYYRPrrerwkhwqAekgeRFYNnTLPmLCQvCQIPMffepdDPTTqshRrssYeGERYHFCSDGCkDIFedEPEKYvQAWLPVHQIlQGNCGGaDLEdVLrYYniNpGqDNgDaegSPdQdRWRnWrGdkPAA</consensus>
      <children>
        <node>
        <name>N520</name>
        <user_name>N520</user_name>
        <dist_to_parent>0.278051</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.259526</creation_cost>
        <subtree_weight>3</subtree_weight>
        <consensus>-----REKYASLTRDLDWEtSYqdmdkVFPhIYdeFEGIKItDWsKWEDPFRLTMDAYWKYQAEKEKKLYAIfDAFAQNNQLNVSDaRYlNAiKLFLTGVTPLEYQAHRGYAHVGRqFrGvGARVAcQMQSIDELRHVQTQIHtMSHYNKFFdGFDWaHdhMHDRVWYLSVPKSFFEDAaRSAGPFEFltAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEVVKFLLEQHEDNIVQKWIDKWFWRGtRLLtLVSGMMMDYMLPVMSWKEAWeEyYFEQAGGALFKDLaRYGIRMPKYhEVAtKEKEHiSHQAWWtFYNygHAAaFHTWiPptdEEMDWLSEKYPDTFDKYYRPrwerakmmeAgkrerFYnntLPQLCQtCQIPMtFtegDppTqcyRrssYhGERYHFCSDGCKDIFddEPEKYvQAWLPVHQIfQGNCGGadLEdVLrWYhLNpGdDNdDAhGSPDQERWRKWKGQGEAA</consensus>
        <children>
          <node>
          <name>N515</name>
          <user_name>N515</user_name>
          <dist_to_parent>0.259526</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.234605</creation_cost>
          <subtree_weight>2.86794</subtree_weight>
          <consensus>-----REKYQKLTRDLDWEFSYQDRKdAFPHIYEEFEGIKITDWSKWEDPFRLTMDAYWKYQAEKEKKLYAIFDAFAQNNQlNVSDaRYvNAIKLFLTGVSPLEYQAyQGYAHVGRQFsGvGARIACQMQSIDELRHVQTQIHAMSHYNKFFDGFDWaHsHMHDRVWYLSVPKSFFEDARRSAGPFEFLlAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEIIKFLLEQHEDNIVQkWIDKWFWRGTRLLSIVSAMMMDYMLPVMSWKEAWEEyYFEQAGGALFKDLaRYGIRMPKYsDVIvKEKEHvSHQAWWiFYNfgHAAAFHTWiPPtDEEMDWLSEKYPDTFDKYYRPrwElakmmeAgKgerfYnngLPQLCQvCQIPMtftegDPtticyRrssYkGERYHFCSDGCkDIFerEPEKYVQAWLPVHQIfQGNCGGadLEdVLrWYHlnpGdDNdDAHGSPDQERWRKWKGQ----</consensus>
          <children>
            <node>
            <name>N510</name>
            <user_name>N510</user_name>
            <dist_to_parent>0.234605</dist_to_parent>
            <is_subfamily>1</is_subfamily>
            <creation_cost>0.173489</creation_cost>
            <subtree_weight>2.66481</subtree_weight>
            <consensus>-----REKYQKLTRDLGWETTYQPMDKVFPHIYDkFEGIKIHDWDkWEDPFRLTMDAYWKFQgEKERKLYAIIDAFAQNNQLNVTDARYVNALKLFLTGVSPLEYAAHRGFAmAGRhfRGVGARVACQMQSIDELRHaQTQIHTISHYNKYFkgFDglHdhmHDRVWYLSVPKSFFDDA-MTAGPFEFiTAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFMLEQDPdNIVQKWIDKWFWRGYRLLtLVSAMMMDYMLPvMSWKEAWEEyYFEqnGGALFeDLARYGIRMPKYHEqAaKEKDHLSHQiwWtIFYnytaAAahHTWpPepeEMdWLSEKYPdtFDkyYRPRfewwdqqeAgkGeRfYNngLPMLCQTCQIPMaTEPDDPTqICfResEYkGekYHFCSDGCKDIFdgEPEKYVQAWLPVHQIFQGNCGGATLPEVLdWYHLkpGddgdDAH------------------</consensus>
            <children>
              <node>
              <name>N498</name>
              <user_name>N498</user_name>
              <dist_to_parent>0.173489</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.149014</creation_cost>
              <subtree_weight>2.54504</subtree_weight>
              <consensus>-----REKYQKLTRDLGWETTYQPMDkVFPHIYDkFEGIKIHDWDkWEDPFRLTMDAYWKFQsEKERKLYAIIDAFAQNNQLNVTDARYVNALKLFLTGVSPLEYAAHRGFAMAGRhlRGVGARVACQMQSIDELRHaQTQIHTISHYNKYfkgFDglHdhmHDRvWYLSVPKSfFdDA-MTAGPFEFiTAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEViKFMLEQDPdNIVQKWIDKWFWRGYRLLtLVSAMMMDYMLPvMSWKEAWeEiYFEqNGGALFeDLARYGIRMPKYHEqAaKEKDHLSHQiaWsIFYnythAAahHTWpPepeEMdWLSEKYPdtFDkYYRPRfewwqqqeAgkgeRfYNngLPMLCQtCQIPMaTEPDDPTqICfResEYkGekYHFCSDGCKDIFdgEPEKYVQAWLPVHQIFQGNCGGATLPEVLdWYHLkpGdrGDYA-------------------</consensus>
              <children>
                <node>
                <name>N492</name>
                <user_name>N492</user_name>
                <dist_to_parent>0.149014</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0.138033</creation_cost>
                <subtree_weight>2.07843</subtree_weight>
                <consensus>-----REKYQKmTRGLDWETSYQPMDkVFPqIYDtFEGIKIHDWDKWEDPFRLTMDAYWKYQAEKERKLYAVLDSFAQNNQLGItDARYVNAIKLFLTGVSPLEYQAHRGFAHaGRHfrGVGPRVAAQMQSLDELRHAQTQIHTISHYNKYnkgFDGlHphMHDRVWYLSVPKSFFDDA-cTAGPFEFfTAISFaFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGIEVIKFMLEQdPDNIVQKWVDKWFWRGYRlLGLVSAMMMDYMLPIMSWKEAWEIYFtEqAGGALFEDLSRYGLRvPKYADVATkEAEHiSHQVWwtffyyytaAAffhtwpPedEEMaWLSEKYPNTFDKYYRPRfEmWreMeaeKGERFYNNaLPQLCqTCQIPMyTEPgDPTtICFRSSEYKGERYHFCSDGCKDIFDdEPEKfaQSWLPVHQIFQGNCGGAdlpDVLkWYHmnnGeDNgD--------------------</consensus>
                <children>
                  <node>
                  <name>N489</name>
                  <user_name>N489</user_name>
                  <dist_to_parent>0.138033</dist_to_parent>
                  <is_subfamily>0</is_subfamily>
                  <creation_cost>0.134341</creation_cost>
                  <subtree_weight>1.67059</subtree_weight>
                  <consensus>-----REKYQKLTRGLGWETTYQPMDKVFPQIYaeYEGIKIHDWDAWEDPFRLTMDAYWKYQAEKERKLYAVIDSFAQNNQLNITDARYVNALKLFLTGVSPLEYaAHRGFAHVGRHFvGVGPRVACQMQAIDELRHAQTQiHTiSHYNKYNKfFDGLHDarHMhDWYLSVPKSFFDDA-MSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDEARHMTLGLEIIKFMLEQDErNIVQRWIDKWFWRGYRLLsLVSAMMMDYMLPvMSWkEAWEmYFEEqaGaALFdDLSRYGIRkPKYaEVAsKEKdRLSHEVWSTFYNYTHAAAFHTWiPeeEEEmaWLSeKYPdTFDtfyRpYRprweqwqaeKGeRfYNNTLPQLCqTCQIPMFTEPDDPTTICFRSSEYkGEkYHFCSDGCKDIFDdEPEKYVQSWLPVHQIYQGNCGGAslPEVLdWYHLndGqDNgD--------------------</consensus>
                  <children>
                    <node>
                    <name>N472</name>
                    <user_name>N472</user_name>
                    <dist_to_parent>0.134341</dist_to_parent>
                    <is_subfamily>0</is_subfamily>
                    <creation_cost>0.108861</creation_cost>
                    <subtree_weight>1.15235</subtree_weight>
                    <consensus>-----REKYQKFTRDLAWEPSYQKKSDIFPQ--TEFEGIHIHDWDKWEDPFRLTVDAYWKYQAEKERKLYSIIDAFSQNNQLNVTDARYVNALKLFLTGVSPLEYAAHRGFAMAGRQFGGVGPQVACQMQSIDELRHVQTQIHTISQYNKYFNGFDWNH--MHQRVWYLSVPKSFFDDA-MSAGPFEFVTAISFSFEYVLTNLLFMPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFMLEQDERNIVQKWIDKWFWRGYRLLSLVS-MMMDYMLPVMSWKEAWEMYFEENGGALFEDDLSRYGIRMPKYWEVSVKEKEHLSHQLWATFHNFGHAAAFHTWIPEESEMQ-WLSEKYPdTFDkYYRPRFEfWefhqkdKGERWYNNTLPMLCQTCQIPMLTEPDDPTQICYRSSdYNGEKYHFCSDGCKDIFDDEPEKYVQAWLPVHQIYQGNCGGASIPEVLEYYHLVDGQDNKD--------------------</consensus>
                    <children>
                      <node>
                      <name>UniRef100_UPI000BE53A74</name>
                      <user_name>UniRef100_UPI000BE53A74</user_name>
                      <dist_to_parent>0.108861</dist_to_parent>
                      <is_subfamily>0</is_subfamily>
                      <creation_cost>0</creation_cost>
                      <subtree_weight>1</subtree_weight>