<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gtree [ 
<!ELEMENT gtree (node+)>
<!ELEMENT node (name | user_name? | dist_to_parent? | is_subfamily? |
creation_cost? | subtree_weight? | cutoffs? | children? | affinity_vector? |
tre_vector? | pwid_vector? | weighted_counts? | profiles? |
log_odds_vector? | sam_hmm? | alignment?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user_name (#PCDATA)>
<!ELEMENT dist_to_parent (#PCDATA)>
<!ELEMENT is_subfamily (#PCDATA)>
<!ELEMENT creation_cost (#PCDATA)>
<!ELEMENT subtree_weight (#PCDATA)>
<!ELEMENT cutoffs (#PCDATA)>
<!ELEMENT affinity_vector (#PCDATA)>
<!ELEMENT tre_vector (#PCDATA)>
<!ELEMENT pwid_vector (#PCDATA)>
<!ELEMENT weighted_counts (#PCDATA)>
<!ELEMENT profiles (#PCDATA)>
<!ELEMENT log_odds_vector (#PCDATA)>
<!ELEMENT sam_hmm (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT consensus (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT children ((node | noderef)*)>
]>

<gtree>
  <node>
  <name>N1124</name>
  <user_name>N1124</user_name>
  <dist_to_parent>0</dist_to_parent>
  <is_subfamily>0</is_subfamily>
  <creation_cost>0.880133</creation_cost>
  <subtree_weight>3</subtree_weight>
  <consensus>KrLNLKERYAaMTRDLgWETtYQpMDkVFPheYDrFEGIKIHDWDKWEDPFRLTMDAYWKYQaEKEKKLYAIIDAFAQNNqLnVtDARYvNALKLFLTGVtPLEYqAHRGFAHVGRqFrGaGARVACQMQSIDELRHvQTQiHAmSHYNKyFnGFdwaHdHMHDRVWYLSVPKSFFEDAfrSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFlLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLPVMSWkEAWWEmYfEQNGGALFKDLARYGIRmPKYwevAckeKDHiSHQAWwtffYyyaAAaffhtWvPtdEEMdWLSEKYPDTFDkYYRPRfEywrewQAkkGeRFYNkTLPMLCQTCQIPMFTEPgDPTkIcyREsdYeGeKYHFCSDGCKDIFDhEPEKYVQAWLPVHQIYQGNCGGaDLeaVLdYYhinpGrDNlDFeGSEDQKNFAAWRGqpppG</consensus>
  <cutoffs> 2.5 </cutoffs>
  <children>
    <node>
    <name>N1121</name>
    <user_name>N1121</user_name>
    <dist_to_parent>0.880133</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.282576</creation_cost>
    <subtree_weight>1.91146</subtree_weight>
    <consensus>MALLnRaDWYDiARTTNWTPSYVtEsELFPEemSGaqGIPMEaWEtYDEPYKtSYPEYVsIQREKDAGAYSVKAALERSkmfEkADPGWkSilKaHYGAIalgEYAAstaEARMARFgRAPGmRNMATFGMLDEnRHGQLQLYFPHdlckKDRQFDWAHKAyHTNEWaAIAARsfFDDifMaRDAIsiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQiGGPaLQILIENGrKeeAQKlVDiAFWRAWRLFSlLTGpSMDYYTPLEHRkmSFKEFMlEWIVgQFERqLiDLGLDKPWYWDqFlneLDyqHHAyHlGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkcWDVIIDNLlaGkiELTvPETLPIVCNMsQLPIcavPGnGWnVkDYpLeYNGRLYHFgSEiDRWvFqQDPERYagHlnLVDRFLAGqIQPpDLgGALqYMgLaPGEmGDDAHgYAWVeAYrnqRyQKKAA</consensus>
    <children>
      <node>
      <name>N1107</name>
      <user_name>N1107</user_name>
      <dist_to_parent>0.282576</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.216903</creation_cost>
      <subtree_weight>1.1155</subtree_weight>
      <consensus>MALLNRDDWYDiaRdlDWdLSYVDpaeAFPaeWkGagDicgeAWDdWDEPFRVSfRdYVmiQRdKEagVgAireAlVRagaYEKLDdaHkAaSHLHMGTicMVEHMAVTMQSRFcRFAPsaRWRnLGaFGMLDETRHTQLDLRFSHDLLkddPrFDWSQkAFHTdEWaVLAtkNfFDDaMLNADCVEAALATSLTlEHGFTNiQFVALAaDAMaAGDiNfSNLLSSIQTDEARHAQlGFPTLdilMeHDPkARAQkaLDiAFWRStRiFQalTGpaMDYYTPlakRkMSFKEFMLEWIVkHHERILeDYGLkKPWYWDqFeksLdHGHHAlHiGTWFWRPTLFWdPNaGVSkdEReWLneKYPnWEEnWGglWDEIIkNiNadnIEKTLPaTfPmLCNlTnLPiGSAfsdndhaKdeqLtYkGRLYhFDSaiSKWcFElDPERYAGHqNiiDRfIdGQIqPadiaGgLnwMGLTPEVMGeDVfNYaWAgDYAENR------</consensus>
      <children>
        <node>
        <name>N1125</name>
        <user_name>N1125</user_name>
        <dist_to_parent>0.216903</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <consensus>MALLNRDDWYDIARDVDWTLSYVDRAVAFPEEWKGEKDICGTAWDDWDEPFRVSFREYVMVQRDKEASVGAIREAMVRAKAYEKLDDGHKATSHLHMGTITMVEHMAVTMQSRFVRFAPSARWRSLGAFGMLDETRHTQLDLRFSHDLLNDSPSFDWSQRAFHTDEWAVLATRNLFDDIMLNADCVEAALATSLTLEHGFTNIQFVALASDAMEAGDVNFSNLLSSIQTDEARHAQLGFPTLDVMMKHDPK-RAQQILDVAFWRSYRIFQAVTGVSMDYYTPVAKRQMSFKEFMLEWIVKHHERILRDYGLQKPWYWDTFEKTLDHGHHALHIGTWFWRPTLFWDPNGGVSREERRWLNQKYPNWEESWGVLWDEIISNINAGNIEKTLPETLPMLCNVTNLPIGS-HWDRFHLKPEQLVYKGRLYTFDSDVSKWIFELDPERYAGHTNVVDRFIGGQIQPMTIEGVLNWMGLTPEVMGKDVFNYRWAGDYAENR------</consensus>
        <children>
          <node>
          <name>UniRef100_O87082</name>
          <user_name>UniRef100_O87082</user_name>
          <dist_to_parent>0</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>MALLNRDDWYDIARDVDWTLSYVDRAVAFPEEWKGEKDICGTAWDDWDEPFRVSFREYVMVQRDKEASVGAIREAMVRAKAYEKLDDGHKATSHLHMGTITMVEHMAVTMQSRFVRFAPSARWRSLGAFGMLDETRHTQLDLRFSHDLLNDSPSFDWSQRAFHTDEWAVLATRNLFDDIMLNADCVEAALATSLTLEHGFTNIQFVALASDAMEAGDVNFSNLLSSIQTDEARHAQLGFPTLDVMMKHDPK-RAQQILDVAFWRSYRIFQAVTGVSMDYYTPVAKRQMSFKEFMLEWIVKHHERILRDYGLQKPWYWDTFEKTLDHGHHALHIGTWFWRPTLFWDPNGGVSREERRWLNQKYPNWEESWGVLWDEIISNINAGNIEKTLPETLPMLCNVTNLPIGS-HWDRFHLKPEQLVYKGRLYTFDSDVSKWIFELDPERYAGHTNVVDRFIGGQIQPMTIEGVLNWMGLTPEVMGKDVFNYRWAGDYAENR------</sequence>
          </node>
        </children>
        </node>
        <node>
        <name>N1126</name>
        <user_name>N1126</user_name>
        <dist_to_parent>0.216903</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <consensus>--LLNRDDWYDTSRNLDWDLSYVDPSEAFPASWSGAGDVPTEAWDKWDEPFRVSYRDYVRIQREKESGVKAVSNALVRSGTYEKLDPAHVAASHLHMGTTCMVEHMAVTMQSRFCRFAPTPRWRNLGVFGMLDETRHTQLDLRFSHDLLKQDPRFDWSQKAFHTNEWGVLAVKNFFDDAMLNADCVEAALATSLTVEHGFTNVQFVALAADAMAAGDINWSNLLSSIQTDEARHAQQGFPTLSILMEHD-PARAQKALDIAFWRSTRLFQTLTGPAMDYYTPLDQRKMSFKEFMLEWIVNHHERILEDYGLKKPWYWDQFMYSLEHGHHAMHLGTWFWRPTLFWKPNAGVSKDEREWLREKYPTWEENWGGMWDEIIKNVNTDQIEKTLPATFPSLCNLTQLPLGSAFSLNDLA-DHSLTYNGRLYHFDSAISKWCFEQDPERYAGHQNIIDRVIDGQIVPADLAGGLSYMGLTPEVMGEDVYNYAWAKDY----------</consensus>
        <children>
          <node>
          <name>UniRef100_A0A0D8HMT3</name>
          <user_name>UniRef100_A0A0D8HMT3</user_name>
          <dist_to_parent>0</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>--LLNRDDWYDTSRNLDWDLSYVDPSEAFPASWSGAGDVPTEAWDKWDEPFRVSYRDYVRIQREKESGVKAVSNALVRSGTYEKLDPAHVAASHLHMGTTCMVEHMAVTMQSRFCRFAPTPRWRNLGVFGMLDETRHTQLDLRFSHDLLKQDPRFDWSQKAFHTNEWGVLAVKNFFDDAMLNADCVEAALATSLTVEHGFTNVQFVALAADAMAAGDINWSNLLSSIQTDEARHAQQGFPTLSILMEHD-PARAQKALDIAFWRSTRLFQTLTGPAMDYYTPLDQRKMSFKEFMLEWIVNHHERILEDYGLKKPWYWDQFMYSLEHGHHAMHLGTWFWRPTLFWKPNAGVSKDEREWLREKYPTWEENWGGMWDEIIKNVNTDQIEKTLPATFPSLCNLTQLPLGSAFSLNDLA-DHSLTYNGRLYHFDSAISKWCFEQDPERYAGHQNIIDRVIDGQIVPADLAGGLSYMGLTPEVMGEDVYNYAWAKDY----------</sequence>
          </node>
        </children>
        </node>
      </children>
      </node>
      <node>
      <name>N1118</name>
      <user_name>N1118</user_name>
      <dist_to_parent>0.282576</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.233383</creation_cost>
      <subtree_weight>1.62825</subtree_weight>
      <consensus>MAlLeRaDWYDlARTTNWTPsYVTEsELFPEeMSGaqGIPMEkWEtYDEPYKtTYPEYVsIQREKDAGAYSVKAALERSrmFEdADPGWkSiLKAHYGAIALGEYAAssAEARMARFGRAPGmRNMATFGMLDEnRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDiFMaRDAISiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQIGGPALQILIENGrKEEAQKLVDiAIWRAWRLFSLLTGpSMDYYTPLEHRkqSFKEFMtEWIVgQFERqLiDLGLDkPWYWDqFlnELDyQHHAYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTFGKcWDVIIDNLlaGkpELTvPETLPIVCNMSQLPIcavPGNGWnVkDYpLEYNGRlYHFgSEiDRWVFQQDPERYadHltLVDRFLAGqIQPPDLgGALqYMgLAPGEcGDDAHgYAWVEAYrnqRyQKKAA</consensus>
      <children>
        <node>
        <name>N1094</name>
        <user_name>N1094</user_name>
        <dist_to_parent>0.233383</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0.162797</creation_cost>
        <subtree_weight>1.39948</subtree_weight>
        <consensus>MALLeRaDWYDiARTTNWTPsYVTEsELFPeeMsGAqGIPMEkWEtYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdYCaKDRQFDWAHKAYHTNEWAAIAARSFFDDifMsRDAIsVAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIENGRKEEAQKkVDIAIWRAWRLFSlLTGPsMDYYTPLEHRKQSFKEFMtEWIVGQFERtLIDLGLDKPWYWDQFinefDyQHHaYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkCWDVIIDNLLaGkpELTVPETLPIVCNMSQLPIcaVPGNGWNVKDYpLEYNGRLYHFGSEiDRWVFQQDPeRYrdHlTLVDRFLAGqIQPmDLgGALkYMnLAPGEcGDDAHdYAWVEAYknqRyQKKAA</consensus>
        <children>
          <node>
          <name>UniRef100_Q00456</name>
          <user_name>UniRef100_Q00456</user_name>
          <dist_to_parent>0.162797</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <sequence>MAMHPRKDWYELTRATNWTPSYVTEEQLFPERMSGHMGIPLEKWESYDEPYKTSYPEYVSIQREKDAGAYSVKAALERAKIYENSDPGWISTLKSHYGAIAVGEYAAVTGEGRMARFSKAPGNRNMATFGMMDELRHGQLQLFFPHEYCKKDRQFDWAWRAYHSNEWAAIAAKHFFDDIITGRDAISVAIMLTFSFETGFTNMQFLGLAADAAEAGDYTFANLISSIQTDESRHAQQGGPALQLLIENGKREEAQKKVDMAIWRAWRLFAVLTGPVMDYYTPLEDRSQSFKEFMYEWIIGQFERSLIDLGLDKPWYWDLFLKDIDELHHSYHMGVWYWRTTAWWNPAAGVTPEERDWLEEKYPGWNKRWGRCWDVITENVLNDRMDLVSPETLPSVCNMSQIPLVGVPGDDWNIEVFSLEHNGRLYHFGSEVDRWVFQQDPVQYQNHMNIVDRFLAGQIQPMTLEGALKYMGFSIEEMGKDAHDFAWADKCK---------</sequence>
          </node>
          <node>
          <name>N1093</name>
          <user_name>N1093</user_name>
          <dist_to_parent>0.162797</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.155684</creation_cost>
          <subtree_weight>1.32823</subtree_weight>
          <consensus>MALLeRaaWYDiARTTNWTPkYVTEsELFPdeMsGAqGiPMEkWEtYDEPYKtsYPEYVsIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDlfMsRdAIdiaIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIaNGRKEeAQKlVDIAIaRAWRLFSlLTGpsMDYaTPLeHRKeSFKEFMtEWIVgQFERtLiDLGLDkPWYWDQfinefDyQHHamhlGiWFWRPTVWWNPAAGvTPdcRDWLEEKYPGWNDTfGkaWDVIIDNLlaGkpELTVPETLPIVCNMSQLPIcatPGNGWnVKDYpLEYnGRlYHFgSEiDRWvFQQDPeRYrdHlTLVDRFLAGlIQPpDLgGALqYMnLAPGEcGDDAHhYaWVEAYrnqRyQKKAA</consensus>
          <children>
            <node>
            <name>N952</name>
            <user_name>N952</user_name>
            <dist_to_parent>0.155684</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.0458436</creation_cost>
            <subtree_weight>1.02591</subtree_weight>
            <consensus>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEAYRNQRYQKKAA</consensus>
            <children>
              <node>
              <name>UniRef100_Q46PB0</name>
              <user_name>UniRef100_Q46PB0</user_name>
              <dist_to_parent>0.0458436</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>MALLERAAWYDIARTTNWTPTYVAESDLFPEVMAGAQGVPMEIWETYDEPYKTSYPEYVRIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCPKDRQFDWAHKAYHTNQWGAIAARSTFDDLFMSRSAIEIAVMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIANGRKEQAQQLVDVAIARAWRLFSLLTGTSMDYATPLQHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTVWWNPAAGMTPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGRKELTVPETLPIVCNMSQLPICAVPGNGWNVRDYPLEYNGRTYHFNSEIDRWVFQQDPVRYRDHLTLVDRFLAGHIQPPDLGGALRYMNLAPGEIGDDAHQYAWVEAYRRQREQNKAA</sequence>
              </node>
              <node>
              <name>N662</name>
              <user_name>N662</user_name>
              <dist_to_parent>0.0458436</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.00179656</creation_cost>
              <subtree_weight>1.00069</subtree_weight>
              <consensus>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYaWVEAYRNQRYQKKAA</consensus>
              <children>
                <node>
                <name>UniRef100_Q51939</name>
                <user_name>UniRef100_Q51939</user_name>
                <dist_to_parent>0.00179656</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEAYRNQRYQKKAA</sequence>
                </node>
                <node>
                <name>UniRef100_Q9EZP0</name>
                <user_name>UniRef100_Q9EZP0</user_name>
                <dist_to_parent>0.00179656</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYPWVEAYRNQRYQKKAA</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
            <node>
            <name>N1092</name>
            <user_name>N1092</user_name>
            <dist_to_parent>0.155684</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.172954</creation_cost>
            <subtree_weight>1.17962</subtree_weight>
            <consensus>MalLNReDWYDLARTTNWTPKYVTEdELFPaElSGafDIPMEKWEaYDEPYKQTYPEYVkVQREKDSGAYSVKAALERSgffEkADPGWkSVMKLHFGAIaLaEYAASTAEARMaRFAKAPGcRNMATfGSMDEIRHGQIQLYFPHEHVSKDRQFDWAHKAfHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPaLQILIENGkKaEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMlEWIVaQFERaLhDLGLDKPWYWDiFLQQLDQQHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNDTWGQCWDVIIDNLVdGkpELTlPETLPIVCNMCNLPINYTPGNaWNVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMnLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHdYaWVEaYKQkRmkK---</consensus>
            <children>
              <node>
              <name>UniRef100_O87798</name>
              <user_name>UniRef100_O87798</user_name>
              <dist_to_parent>0.172954</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>MSMLKREDWYDLTRTTNWTPKYVTENELFPEEMSGARGISMEAWEKYDEPYKITYPEYVSIQREKDSGAYSIKAALERDGFVDRADPGWVSTMQLHFGAIALEEYAASTAEARMARFAKAPGNRNMATFGMMDENRHGQIQLYFPYANVKRSRKWDWAHKAIHTNEWAAIAARSFFDDMMMTRDSVAVSIMLTFAFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQQGGPSLKILVENGKKDEAQQMVDVAIWRSWKLFSVLTGPIMDYYTPLESRNQSFKEFMLEWIVAQFERQLLDLGLDKPWYWDQFMQDLDETHHGMHLGVWYWRPTVWWDPAAGVSPEEREWLEEKYPGWNDTWGQCWDVITDNLVNGKPELTVPETLPTICNMCNLPIAHTPGNKWNVKDYQLEYEGRLYHFGSEADRWCFQIDPERYKNHTNLVDRFLKGEIQPADLAGALMYMSLEPGVMGDDAHDYEWVKAYQKK-------</sequence>
              </node>
              <node>
              <name>N1088</name>
              <user_name>N1088</user_name>
              <dist_to_parent>0.172954</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.154339</creation_cost>
              <subtree_weight>1.08056</subtree_weight>
              <consensus>MalLNrtDWYDlARTTNcsPeirhedelfpaelegrfDIPMEKWEaYDEPYKQTYPEYVkVQREKDaGaYSVKAALERSkifEkADPGWkSVlKlHfGAIplaEYAAfqAeaRleRcakapGcaNMATlGSlDEIRHaQiQLYFPHEHVSKDRQFDWAaKAfdTNEWAAIAaRHFFDDIMMaRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDfTFaSLISSIQTDESRHAQIGGPaLQIfIENGqKaEAQKKVDIAFWRAWRLFSiLTGPiMDYYTPLEHRkQSFKEFMnEWIVeQFERaihDLGLDKPWYWDiFLeQLDQQHHGMHLGVWfWRPTVWWNPaAGVTPaERDWLEEKYPGWNdTWGhCWDVIIdNLVdGntalTlPETLPIVCNMcnLPINYTPGdaWaVkDYqLEYNGRLYHFGSEPDRWcFEQEPERYAGHMsLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHgYaWVEiYKQlRmkK---</consensus>
              <children>
                <node>
                <name>UniRef100_O07068</name>
                <user_name>UniRef100_O07068</user_name>
                <dist_to_parent>0.154339</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MVLLNSVDWYDLARTTNCSPEIRHRKRTISASVERRVDIPMEKWEGYDEPYKQTYPEYVRVQREKDSGAYSVKAALERSQIYEKADPGWKSVMKQHYGAISLAEYAAFQ-RLRLERCARLQGCANMATMGSLDEIRHGQIQLYFPHEHVSKDRQFDWAAKAYHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPALQIFIENGQKAEAQKKVDIAFWRAWRLFSILTGPVMDYYTPLEHRKQSFKEFMNEWIVVQFERALTDLGLDKPWYWDTFLQQLDQQHHGMHLGVWFWRPTVWWNPAAGVTPAERDWLEEKYPGWNSTWGQCWDVIIENLVDGNVAQTYPETLPIVCNMSQLPINYTPGDAWAVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMSLVDRFLAGLIQPMDLGGALKYMDLAPGEIGDDAHNYAWVEIYKQMRMNK---</sequence>
                </node>
                <node>
                <name>UniRef100_P95408</name>
                <user_name>UniRef100_P95408</user_name>
                <dist_to_parent>0.154339</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>MAVLNRTDWYDVARTTNWTPKYVTEDELFPPELSGSFDIPMEKWEAYDEPYKQTYPEYVKVQREKDAGVYSVKAALERSKMFENADPGWQSVLKLHFGAIPSGEYAASTAEARMMRFSKAPGMRNMATLGSMDEIRHAQLQLYFPHEHVSKDRQFDWAHKAFDTNEWAAIASRHFFDDIMMARDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDFTFSSLISSIQTDESRHAQIGGPTLQILIENGRKEEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMQEWIVEQFERSIHDLGLDKPWYWDIFLEQLDQQHHGMHLGVWYWRPTVWWNPTAGVTPEERDWLEEKYPGWNDTWGHCWDVIIDNLVEGRTELTLPETLPIVCNMCNLPINYTPGNGWNVQDYSLEYNGRLYHFGSEPDRWIFEQEPERYAGHMTLVDRFLAGLIQPMDLGGALAYMDLAPGESGDDAHGYSWVEVYKQLRTKK---</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
          </children>
          </node>
        </children>
        </node>
        <node>
        <name>N1117</name>
        <user_name>N1117</user_name>
        <dist_to_parent>0.233383</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.254591</creation_cost>
        <subtree_weight>1.13731</subtree_weight>
        <consensus>MPKLaRrDwYDlARDmNWaFgYVSEddVFPEELSgsfgihaEeWlaWDEPYKiTYREYVHNQagKDdgiYSiknaIARSaLfdkLDaGWKSaIkAHYGAIpmPEYfASIGEARMaRFGRAAAWRNmAaFGTLDEcRHGQaQafFPYcLiGKdPqaDWAhKAfHTNdWgViAaRqLFDDMFtANDAlSiAiQLTFTfETGFTNLQFLGMAaDAihVGDiEFGaLISSIQTDEARHaQQGEPTiKIlaegGhKaeaQfLiDhMFWRSWklFALLTGiSMDYYTPLEhRTMSFKEFiedWickQFmDQFkDfGlevPWYWEeFlnELdWvHHAiHlGVWfWRPTVWWNPDAGVSAaERdWLEeKYPGWNdrFGKlWDaIGdNiRaGkiEaTfPaTLPiVCNcChiPIcrAagaGaaarAAilrHnGRdllFCcEpCeWifarqPERfagHlSlVDRFLAGeIqPPdLeGaLaYMGisPaeaGnDAqGYAWagASR---------</consensus>
        <children>
          <node>
          <name>N1127</name>
          <user_name>N1127</user_name>
          <dist_to_parent>0.254591</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>MPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGAGALASAAPLRHTGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQA-----------</consensus>
          <children>
            <node>
            <name>UniRef100_Q2JGJ2</name>
            <user_name>UniRef100_Q2JGJ2</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>MPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGAGALASAAPLRHTGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQA-----------</sequence>
            </node>
          </children>
          </node>
          <node>
          <name>N1128</name>
          <user_name>N1128</user_name>
          <dist_to_parent>0.254591</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICS-PSIGQAPR--ITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASR---------</consensus>
          <children>
            <node>
            <name>UniRef100_A5ECB8</name>
            <user_name>UniRef100_A5ECB8</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICS-PSIGQAPR--ITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASR---------</sequence>
            </node>
          </children>
          </node>
        </children>
        </node>
      </children>
      </node>
    </children>
    </node>
    <node>
    <name>N1123</name>
    <user_name>N1123</user_name>
    <dist_to_parent>0.880133</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.302316</creation_cost>
    <subtree_weight>3</subtree_weight>
    <consensus>KRLNLKERYAaMTRDLgWETTYQpMDkVFPHcYDrFEGIKIHDWDKWEDPFRLTMDAYWKYQaEKEKKLYAIIDAFAQNNqLnVtDARYvNALKLFLTGVTPLEYqAHRGFAHVGRqFrGaGARVACQMQSIDELRHvQTQiHAMSHYNKyFnGFdwsHdHMHDRVWYLSVPKSFFEDAArSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFlLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLPVMSWkEAWWEmYfEQNGGALFKDLARYGIRmPKYwevAckeKDHiSHQAWwtffYyyaAAaffhtWvPtdEEMdWLSEKYPDTFDkYYRPRfEywrewQAkkGeRFYNkTLPMLCQTCQIPMFTEPgDPTkIcyREsdYeGeKYHFCSDGCKDIFDhEPEKYVQAWLPVHQIYQGNCGGaDLeaVLdYYhinpGrDNlDFeGSEDQKNFAAWRGqpppG</consensus>
    <children>
      <node>
      <name>N1120</name>
      <user_name>N1120</user_name>
      <dist_to_parent>0.302316</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.281677</creation_cost>
      <subtree_weight>3</subtree_weight>
      <consensus>KRLNLKERYAaMTRDLgWETtYQpMDkVFPHcYDrFEGIKIHDWDKWEDPFRLTMDAYWKYQaEKEKKLYAIIDAFAQNNqLnVtDARYvNALKLFLTGVTPLEYqAHRGFAHVGRqFrGaGARVACQMQSIDELRHvQTQiHAMSHYNKyFnGFdwsHdHMHDRVWYLSVPKSFFEDAarSAGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFlLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLPVMSWkEAWWEmYfEQNGGALFKDLARYGIRmPKYwevAckeKDHiSHQAWwtffYyyaAAaffhtWvPtdEEMdWLSEKYPDTFDkYYRPRfEywrewQAkkGeRFYNkTLPMLCQTCQIPMFTEPgDPTkIcyREsdYeGeKYHFCSDGCKDIFDhEPEKYVQAWLPVHQIYQGNCGGaDLeaVLdYYhinpGrDNlDFeGSEDQKNFAAWRGqpppG</consensus>
      <children>
        <node>
        <name>N1104</name>
        <user_name>N1104</user_name>
        <dist_to_parent>0.281677</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.195636</creation_cost>
        <subtree_weight>3</subtree_weight>
        <consensus>-----KERYAAMTRGLGWETTYQPMDKVFPqcYDrYEGIKIHDWDKWEDPFRLTMDAYWKYQGEKEKKLYAVIDAFaQNNQLGVTDARYINALKLFlqGVsPLEYaAHRGFAHVGRhFtGeGARVACQMQSIDELRHaQTQtHAiShYNKYFNGFhhsHdHwhDRVWYLSVPKSFFEDA-mSAGPFEFlTAISFSFEYVLTNLLFVPFMSGAAYNGDMsTVTFGFSAQSDESRHMTLGIECIKFmLEQDPDNIVQRWIDKWFWRGYRLLTLVSAMMMDYMLPVMSWkEAWeEMYaEqNGGALFkDLARYGIRePKGWeqACeeKDHISHQAWwTfFYnynAAAaFHTWvPsedEMaWLSeKYPDtFDkYYRPRFEyWrEqQAkaGnRFYNKTLPMLCQTCQIPMFTEPGDPTKICYRESDYlGnKYHFCSDGCKeIFDhEPEKYVQAWLPVHQIYQGNCGfdpLAAVLDYYhlnvGRDNlDFEGSEDQKNFAAWRGQpshG</consensus>
        <children>
          <node>
          <name>N1086</name>
          <user_name>N1086</user_name>
          <dist_to_parent>0.195636</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0.14901</creation_cost>
          <subtree_weight>2.26615</subtree_weight>
          <consensus>-----KDRYAAMTRGLGWETTYQPMDKVFPQVYDrYEGIKIHDWDKWEDPFRLTMDAYWKYQGEKEKKLYAVIDAFaQNNfLGVTDARYINALKLFIQGVTPLEYyAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTETHAmStYNKYFNGfHHSnpHWFDRVWYLSVPKSFFEDA-yTAGPFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFmLEQDPDNIVQRWIDKWFWRGYRLLTLVSAMMMDYMLPVMSWKEAW-EMYAEQNGGALFKDLARYGIREPKGWqdACEGKDHISHQAWsTFFYgfNAAAaFHTWVPtEdEMaWLSAKYPDSFDKYYRPRFEyWREqQAkaGNRFYnKTLPMLCQTCQIPMFTEPGDPTKICYRESDYlGnKYHFCSDHCKEIFDHEPEKYVQAWLPVHQIYQGNCGFDPLAAVLDYYevemGRDNLDFEGSEDQKNFAAWRGQppPG</consensus>
          <children>
            <node>
            <name>N1073</name>
            <user_name>N1073</user_name>
            <dist_to_parent>0.14901</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.128696</creation_cost>
            <subtree_weight>1.81949</subtree_weight>
            <consensus>-----KDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWvDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYyAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTETHAmSTYNKFFNGfHHSNpHWFDRVWYLSVPKSFFEDA-YSaGPFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQPVMSWRESW-EMYAEQNGGALFKDLARYGIREPKGWqDACEGKDHISHQAWsTFFYgFNAAAAFHTWVPtEdEMAWLSAKYPDSFDRYYRPRFEYWgEaQAkAGNRFYmKTLPMLCQTCQIPMFTEPGDPTKIgARESDYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIYQGNCGFDPLAAVLDYYEVnmGRDNLDFEGSEDQKNFAAWRGQppPG</consensus>
            <children>
              <node>
              <name>UniRef100_UPI000E5AFDB0</name>
              <user_name>UniRef100_UPI000E5AFDB0</user_name>
              <dist_to_parent>0.128696</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>-----KDRYAAMTRGLAWETTYQPMDKVFP--YDQYEGIRIHDWDRWEDPFRLTMDAYWKYQGEKEKKLYAVIEAFAQNNQLGVTDARYINALKLFLQGVTPLEYCAHRGFAHVGRQFRGAGARVACQMQSIDELRHYQTETHALSQYNKYFNGM-HRANHWYDRVWYLSVPKSFFEDA-MSAGPFEFLTAVSFSFEYVLTNLLFVPFMSGAAHNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPANIVQRWIDKWFWRGYRLLTIV-AMMQDYMLPVMSWKEAW-EMYAESNGGALFKDLARYGIREPAGWADACEGKHHISHQ-AWNAFYNYNVAAPLHTWVPQDSELDWLSEKYPESFDALYRPRLEYFRE-RQQQGERFYSKTLPMLCNTCQIPMFTEPGRPDEISYREGRYLGDVYHFCSDHCKGIFEQEPEKYVQSWLPVHQIYQGNCGFDPLAEVLAYYEMGEGTDNLDFEGSQDQKNFAAWRGEST--</sequence>
              </node>
              <node>
              <name>N1060</name>
              <user_name>N1060</user_name>
              <dist_to_parent>0.128696</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.115184</creation_cost>
              <subtree_weight>1.81268</subtree_weight>
              <consensus>-----KDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWvDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYyAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTETHAmSTYNKFFNGfHHSNpHWFDRVWYLSVPKSFFEDA-YSaGPFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQPVMSWRESW-EMYAEQNGGALFKDLARYGIREPKGWqDACEGKDHISHQAWsTFFYgFNAAAAFHTWVPtEdEMAWLSAKYPDSFDRYYRPRFEYWgEaQAkAGNRFYmKTLPMLCQTCQIPMFTEPGDPTKIgARESDYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIYQGNCGFDPLAAVLDYYEVnmGRDNLDFEGSEDQKNFAAWRGQppPG</consensus>
              <children>
                <node>
                <name>N1045</name>
                <user_name>N1045</user_name>
                <dist_to_parent>0.115184</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0.100845</creation_cost>
                <subtree_weight>1.78562</subtree_weight>