<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gtree [ 
<!ELEMENT gtree (node+)>
<!ELEMENT node (name | user_name? | dist_to_parent? | is_subfamily? |
creation_cost? | subtree_weight? | cutoffs? | children? | affinity_vector? |
tre_vector? | pwid_vector? | weighted_counts? | profiles? |
log_odds_vector? | sam_hmm? | alignment?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user_name (#PCDATA)>
<!ELEMENT dist_to_parent (#PCDATA)>
<!ELEMENT is_subfamily (#PCDATA)>
<!ELEMENT creation_cost (#PCDATA)>
<!ELEMENT subtree_weight (#PCDATA)>
<!ELEMENT cutoffs (#PCDATA)>
<!ELEMENT affinity_vector (#PCDATA)>
<!ELEMENT tre_vector (#PCDATA)>
<!ELEMENT pwid_vector (#PCDATA)>
<!ELEMENT weighted_counts (#PCDATA)>
<!ELEMENT profiles (#PCDATA)>
<!ELEMENT log_odds_vector (#PCDATA)>
<!ELEMENT sam_hmm (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT consensus (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT children ((node | noderef)*)>
]>

<gtree>
  <node>
  <name>N2</name>
  <user_name>N2</user_name>
  <dist_to_parent>0</dist_to_parent>
  <is_subfamily>1</is_subfamily>
  <creation_cost>0.00179656</creation_cost>
  <subtree_weight>1.00069</subtree_weight>
  <consensus>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYaWVEAYRNQRYQKKAA</consensus>
  <cutoffs> 2.5 </cutoffs>
  <children>
    <node>
    <name>UniRef100_Q51939</name>
    <user_name>UniRef100_Q51939</user_name>
    <dist_to_parent>0.00179656</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0</creation_cost>
    <subtree_weight>1</subtree_weight>
    <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEAYRNQRYQKKAA</sequence>
    </node>
    <node>
    <name>UniRef100_Q9EZP0</name>
    <user_name>UniRef100_Q9EZP0</user_name>
    <dist_to_parent>0.00179656</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0</creation_cost>
    <subtree_weight>1</subtree_weight>
    <sequence>MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPGNGWIVKDYPLDYKGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYPWVEAYRNQRYQKKAA</sequence>
    </node>
  </children>
  </node>
</gtree>
