<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE gtree [ 
<!ELEMENT gtree (node+)>
<!ELEMENT node (name | user_name? | dist_to_parent? | is_subfamily? |
creation_cost? | subtree_weight? | cutoffs? | children? | affinity_vector? |
tre_vector? | pwid_vector? | weighted_counts? | profiles? |
log_odds_vector? | sam_hmm? | alignment?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user_name (#PCDATA)>
<!ELEMENT dist_to_parent (#PCDATA)>
<!ELEMENT is_subfamily (#PCDATA)>
<!ELEMENT creation_cost (#PCDATA)>
<!ELEMENT subtree_weight (#PCDATA)>
<!ELEMENT cutoffs (#PCDATA)>
<!ELEMENT affinity_vector (#PCDATA)>
<!ELEMENT tre_vector (#PCDATA)>
<!ELEMENT pwid_vector (#PCDATA)>
<!ELEMENT weighted_counts (#PCDATA)>
<!ELEMENT profiles (#PCDATA)>
<!ELEMENT log_odds_vector (#PCDATA)>
<!ELEMENT sam_hmm (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT consensus (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT children ((node | noderef)*)>
]>

<gtree>
  <node>
  <name>N1140</name>
  <user_name>N1140</user_name>
  <dist_to_parent>0</dist_to_parent>
  <is_subfamily>0</is_subfamily>
  <creation_cost>0.90579</creation_cost>
  <subtree_weight>3</subtree_weight>
  <consensus>MRRGSVAGPGGFGpNpAaDTptakKKLgLKerYaaMTRDLgWETtYQpMDkVFPeEYDrFEGIKIHDWDKWEDPFRLTMDAYWKYQaEKEKKLYAIIDAFAQNNqLnVtDARYvNALKLFLTGVTPLEYqAHRGFAHVGRqFrGaGARVACQMQSIDELRHaQTQAiHAmSHYNKyFNGfHdfnHMHDRVWYLSVPKSFFEDArSAGDPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFlLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLPLEKRVMSWkEAWEmYFEQNGGALFKDYGIRmPKywevAceeKDHiSHQAWstFYNYgaAAaFHTWvPitedEMdWLSEKYPDFDkyYRPRyepwrEqaqaGkGERFYNkTLPMLCQTCQIPMlFTafTEPgDPTkIcyRESdYeGeKYHFCSDGCKDIFDhEPEKYVQAWLPVHQIYQGNCGGpDLeaVLdYYhinpGrDNlDFeGSeDQKNFAAWRGqApaaed</consensus>
  <cutoffs> 2.5 </cutoffs>
  <children>
    <node>
    <name>N1137</name>
    <user_name>N1137</user_name>
    <dist_to_parent>0.90579</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.280261</creation_cost>
    <subtree_weight>1.86161</subtree_weight>
    <consensus>MRRGSVAGPGGFGPRPWGNTKEASMAlLnRaDWYDiARTTNWTPSYVtEsELFPEemSGaqGIPMEaWEtYDEPYKtSYPEYVsIQREKDAGAYSVKAALERSkmfEkADPGWkSilKaHYGAIalgEYAAstaEARMARFgRAPGmRNMATFGMLDEnRHGQLQLYFPHdlckKDRQFDWAHKAyHTNEWaAIAARsfFDDifMaRDAIsiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQiGGPaLQILIENGrKeeAQKLVDiAFWRAWRLFSlLTGpSMDYYTPLEHRkmSFKEFMlEWIVgQFERqLiDLGLDKPWYWDqFlneLDyqHHAyHlGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkcWDVIIDNLlaGkiELTvPETLPIVCNMsQLPIcavPGytnGwiwndaPlqLeYNGRLYHFgSEiDRWvFqQDPERYagHlnLVDRFLAGqIQPpDLgGALqYMgLaPGEmGDDAHgYAWVeAaaaaATGARAARR</consensus>
    <children>
      <node>
      <name>N1129</name>
      <user_name>N1129</user_name>
      <dist_to_parent>0.280261</dist_to_parent>
      <is_subfamily>1</is_subfamily>
      <creation_cost>0.214763</creation_cost>
      <subtree_weight>1.16121</subtree_weight>
      <consensus>------------------------MALLNRDDWYDiaRdlDWdLSYVDpaeAFPaeWkGagDicgeAWDdWDEPFRVSfRdYVmiQRdKEagVgAireAlVRagaYEKLDdaHkAaSHLHMGTicMVEHMAVTMQSRFcRFAPsaRWRnLGaFGMLDETRHTQLDLRFSHDLLkddPrFDWSQkAFHTdEWaVLAtkNfFDDaMLNADCVEAALATSLTlEHGFTNiQFVALAaDAMaAGDiNfSNLLSSIQTDEARHAQlGFPTLdilMeHDPaRAaQiaLDiAFWRStRiFQalTGpaMDYYTPlakRkMSFKEFMLEWIVkHHERILeDYGLkKPWYWDqFeksLdHGHHAlHiGTWFWRPTLFWdPNaGVSkdEReWLneKYPnWEEnWGglWDEIIkNiNadnIEKTLPaTfPmLCNlTnLPiGSafD----SlfdLadeqLtYkGRLYhFDSaiSKWcFElDPERYAGHqNiiDRfIdGQIqPadiaGgLnwMGLTPEVMGeDVfNYaWAK--------------</consensus>
      <children>
        <node>
        <name>UniRef100_A0A0D8HMT3</name>
        <user_name>UniRef100_A0A0D8HMT3</user_name>
        <dist_to_parent>0.214763</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>---------------------------LNRDDWYDTSRNLDWDLSYVDPSEAFPASWSGAGDVPTEAWDKWDEPFRVSYRDYVRIQREKESGVKAVSNALVRSGTYEKLDPAHVAASHLHMGTTCMVEHMAVTMQSRFCRFAPTPRWRNLGVFGMLDETRHTQLDLRFSHDLLKQDPRFDWSQKAFHTNEWGVLAVKNFFDDAMLNADCVEAALATSLTVEHGFTNVQFVALAADAMAAGDINWSNLLSSIQTDEARHAQQGFPTLSILMEHDPAR-AQKALDIAFWRSTRLFQTLTGPAMDYYTPLDQRKMSFKEFMLEWIVNHHERILEDYGLKKPWYWDQFMYSLEHGHHAMHLGTWFWRPTLFWKPNAGVSKDEREWLREKYPTWEENWGGMWDEIIKNVNTDQIEKTLPATFPSLCNLTQLPLGSAF-----SLNDLADHSLTYNGRLYHFDSAISKWCFEQDPERYAGHQNIIDRVIDGQIVPADLAGGLSYMGLTPEVMGEDVYNYAWAK--------------</sequence>
        </node>
        <node>
        <name>UniRef100_O87082</name>
        <user_name>UniRef100_O87082</user_name>
        <dist_to_parent>0.214763</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0</creation_cost>
        <subtree_weight>1</subtree_weight>
        <sequence>------------------------MALLNRDDWYDIARDVDWTLSYVDRAVAFPEEWKGEKDICGTAWDDWDEPFRVSFREYVMVQRDKEASVGAIREAMVRAKAYEKLDDGHKATSHLHMGTITMVEHMAVTMQSRFVRFAPSARWRSLGAFGMLDETRHTQLDLRFSHDLLNDSPSFDWSQRAFHTDEWAVLATRNLFDDIMLNADCVEAALATSLTLEHGFTNIQFVALASDAMEAGDVNFSNLLSSIQTDEARHAQLGFPTLDVMMKHDPKRAQQIL-DVAFWRSYRIFQAVTGVSMDYYTPVAKRQMSFKEFMLEWIVKHHERILRDYGLQKPWYWDTFEKTLDHGHHALHIGTWFWRPTLFWDPNGGVSREERRWLNQKYPNWEESWGVLWDEIISNINAGNIEKTLPETLPMLCNVTNLPIGSHWD-----RFHLKPEQLVYKGRLYTFDSDVSKWIFELDPERYAGHTNVVDRFIGGQIQPMTIEGVLNWMGLTPEVMGKDVFNYRWA---------------</sequence>
        </node>
      </children>
      </node>
      <node>
      <name>N1136</name>
      <user_name>N1136</user_name>
      <dist_to_parent>0.280261</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.242367</creation_cost>
      <subtree_weight>1.60308</subtree_weight>
      <consensus>MRRGSVAGPGGFGPRPWGNTKEASMAlLeRaDWYDlARTTNWTPsYVTEsELFPEeMSGaqGIPMEkWEtYDEPYKtTYPEYVsIQREKDAGAYSVKAALERSrmFEdADPGWkSiLKAHYGAIALGEYAAssAEARMARFGRAPGmRNMATFGMLDEnRHGQLQLYFPHdycaKDRQFDWAHKAYHTNEWaAIAARSfFDDiFMaRDAISiAIMLTFaFETGFTNMQFLGLAADAAEAGDfTFASLISSIQTDESRHAQIGGPALQILIENGrKEEAQKLVDiAIWRAWRLFSLLTGpSMDYYTPLEHRkqSFKEFMtEWIVgQFERqLiDLGLDkPWYWDqFlnELDyQHHAYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTFGKcWDVIIDNLlaGkpELTvPETLPIVCNMSQLPICaVPGytnGwiwndyPldleYNGRlYHFgSEiDRWVFQQDPERYadHltLVDRFLAGqIQPPDLgGALqYMgLAPGEcGDDAHgYAWVEAaaaaATGARAARR</consensus>
      <children>
        <node>
        <name>N1119</name>
        <user_name>N1119</user_name>
        <dist_to_parent>0.242367</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0.16303</creation_cost>
        <subtree_weight>1.5758</subtree_weight>
        <consensus>------------------------MALLeRaDWYDiARTTNWTPsYVTEsELFPeeMsGAqGIPMEkWEtYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSrMFEdADPGWlSiLKaHYGAIALGEYAAmsAEARMARFgRAPGMRNMATFGMLDENRHGQLQLYFPHdYCaKDRQFDWAHKAYHTNEWAAIAARSFFDDifMsRDAIsVAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIENGRKEEAQKkVDIAIWRAWRLFSlLTGPsMDYYTPLEHRKQSFKEFMtEWIVGQFERtLIDLGLDKPWYWDQFinefDyQHHaYHMGVWFWRPTVWWNPAAGVTPdERDWLEEKYPGWNDTWGkCWDVIIDNLLaGkpELTVPETLPIVCNMSQLPICAVPGytNGWiWndydldLEYNGRLYHFGSEiDRWVFQQDPeRYrdHlTLVDRFLAGqIQPmDLgGALkYMnLAPGEcGDDAHdYAWVEA-------------</consensus>
        <children>
          <node>
          <name>N950</name>
          <user_name>N950</user_name>
          <dist_to_parent>0.16303</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.0407675</creation_cost>
          <subtree_weight>1.10746</subtree_weight>
          <consensus>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYKYNGRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEA-------------</consensus>
          <children>
            <node>
            <name>UniRef100_Q46PB0</name>
            <user_name>UniRef100_Q46PB0</user_name>
            <dist_to_parent>0.0407675</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>------------------------MALLERAAWYDIARTTNWTPTYVAESDLFPEVMAGAQGVPMEIWETYDEPYKTSYPEYVRIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCPKDRQFDWAHKAYHTNQWGAIAARSTFDDLFMSRSAIEIAVMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIANGRKEQAQQLVDVAIARAWRLFSLLTGTSMDYATPLQHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTVWWNPAAGMTPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGRKELTVPETLPIVCNMSQLPICAVPG--NGWNVRDYPLE--YNGRTYHFNSEIDRWVFQQDPVRYRDHLTLVDRFLAGHIQPPDLGGALRYMNLAPGEIGDDAHQYAWVEA-------------</sequence>
            </node>
            <node>
            <name>N675</name>
            <user_name>N675</user_name>
            <dist_to_parent>0.0407675</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.00183689</creation_cost>
            <subtree_weight>1.05567</subtree_weight>
            <consensus>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYaWVEA-------------</consensus>
            <children>
              <node>
              <name>UniRef100_Q9EZP0</name>
              <user_name>UniRef100_Q9EZP0</user_name>
              <dist_to_parent>0.00183689</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYPWVEA-------------</sequence>
              </node>
              <node>
              <name>UniRef100_Q51939</name>
              <user_name>UniRef100_Q51939</user_name>
              <dist_to_parent>0.00183689</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MALLERAAWYDIARTTNWTPSYVTESELFPDIMTGAQGVPMETWETYDEPYKTSYPEYVSIQREKDAGAYSVKAALERSRMFEDADPGWLSILKAHYGAIALGEYAAMSAEARMARFGRAPGMRNMATFGMLDENRHGQLQLYFPHDYCAKDRQFDWAHKAYHTNEWGAIAARSTFDDLFMSRSAIDIAIMLTFAFETGFTNMQFLGLAADAAEAGDFTFASLISSIQTDESRHAQIGGPALQILIASGRKEQAQKLVDIAIARAWRLFSLLTGTSMDYATPLHHRKESFKEFMTEWIVGQFERTLIDLGLDLPWYWDQMINEFDYQHHAYQMGIWFWRPTIWWNPAAGITPDCRDWLEEKYPGWNDTFGKAWDVIIDNLLAGKPELTVPETLPIVCNMSQLPICAVPG--NGWIVKDYPLDYK--GRTYHFNSEIDRWVFQQDPLRYRDHLTLVDRFLAGQIQPPNLMGALQYMNLAPGECGDDAHHYAWVEA-------------</sequence>
              </node>
            </children>
            </node>
          </children>
          </node>
          <node>
          <name>N1118</name>
          <user_name>N1118</user_name>
          <dist_to_parent>0.16303</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.169329</creation_cost>
          <subtree_weight>1.37418</subtree_weight>
          <consensus>------------------------MamLnReDWYDLaRTTNWTPkYVTEdeLFPeemSGafdIPMEKWEaYDEPYKqTYPEYVsiQREKDaGAYSVKAALERskiyEnADPGWiStlKlHfGAIalgEYAAsTaEaRMaRFaKAPGnRNMATfGmMDEiRHGQiQLYFPHEhVkKDRQFDWAhKAyHTNEWAAIAARHFFDDIMMtRDAISVgIMLTFgFETGFTNMQFLGLAADAAEAGDhTFASLISSIQTDESRHAQiGGPaLQILIENGkKeEAQKKVDiAfWRAWRLFSVLTGPiMDYYTPLEhRnQSFKEFMlEWIVaQFERsLhDLGLDKPWYWDiFLqdLDeqHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNdTWGqCWDVIidNLVnGrmeLTlPETLPiVCNMcnLPIagtPgytPGdaWNVkDYqLEYNGRLYHFGSEpDRWcFeQdPERYagHMnLVDRFLAGlIQPMDLgGALkYMdLaPGEmGDDAHdYaWVea-------------</consensus>
          <children>
            <node>
            <name>UniRef100_Q00456</name>
            <user_name>UniRef100_Q00456</user_name>
            <dist_to_parent>0.169329</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>------------------------MAMHPRKDWYELTRATNWTPSYVTEEQLFPERMSGHMGIPLEKWESYDEPYKTSYPEYVSIQREKDAGAYSVKAALERAKIYENSDPGWISTLKSHYGAIAVGEYAAVTGEGRMARFSKAPGNRNMATFGMMDELRHGQLQLFFPHEYCKKDRQFDWAWRAYHSNEWAAIAAKHFFDDIITGRDAISVAIMLTFSFETGFTNMQFLGLAADAAEAGDYTFANLISSIQTDESRHAQQGGPALQLLIENGKREEAQKKVDMAIWRAWRLFAVLTGPVMDYYTPLEDRSQSFKEFMYEWIIGQFERSLIDLGLDKPWYWDLFLKDIDELHHSYHMGVWYWRTTAWWNPAAGVTPEERDWLEEKYPGWNKRWGRCWDVITENVLNDRMDLVSPETLPSVCNMSQIPLVGVPGDD----WNIEVFSLEHNGRLYHFGSEVDRWVFQQDPVQYQNHMNIVDRFLAGQIQPMTLEGALKYMGFSIEEMGKDAHDFAWAD--------------</sequence>
            </node>
            <node>
            <name>N1117</name>
            <user_name>N1117</user_name>
            <dist_to_parent>0.169329</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.173021</creation_cost>
            <subtree_weight>1.24909</subtree_weight>
            <consensus>------------------------MalLNReDWYDLARTTNWTPKYVTEdELFPaElSGafDIPMEKWEaYDEPYKQTYPEYVkVQREKDSGAYSVKAALERSgffEkADPGWkSVMKLHFGAIaLaEYAASTAEARMaRFAKAPGcRNMATfGSMDEIRHGQIQLYFPHEHVSKDRQFDWAHKAfHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPaLQILIENGkKaEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMlEWIVaQFERaLhDLGLDKPWYWDiFLQQLDQQHHGMHLGVWYWRPTVWWNPAAGVTPEERDWLEEKYPGWNDTWGQCWDVIIDNLVdGkpELTlPETLPIVCNMCNLPIAHTPNYTPGdaWNVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMnLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHdYaWVEa-------------</consensus>
            <children>
              <node>
              <name>UniRef100_O87798</name>
              <user_name>UniRef100_O87798</user_name>
              <dist_to_parent>0.173021</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0</creation_cost>
              <subtree_weight>1</subtree_weight>
              <sequence>------------------------MSMLKREDWYDLTRTTNWTPKYVTENELFPEEMSGARGISMEAWEKYDEPYKITYPEYVSIQREKDSGAYSIKAALERDGFVDRADPGWVSTMQLHFGAIALEEYAASTAEARMARFAKAPGNRNMATFGMMDENRHGQIQLYFPYANVKRSRKWDWAHKAIHTNEWAAIAARSFFDDMMMTRDSVAVSIMLTFAFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQQGGPSLKILVENGKKDEAQQMVDVAIWRSWKLFSVLTGPIMDYYTPLESRNQSFKEFMLEWIVAQFERQLLDLGLDKPWYWDQFMQDLDETHHGMHLGVWYWRPTVWWDPAAGVSPEEREWLEEKYPGWNDTWGQCWDVITDNLVNGKPELTVPETLPTICNMCNLPIAHTPGNK----WNVKDYQLEYEGRLYHFGSEADRWCFQIDPERYKNHTNLVDRFLKGEIQPADLAGALMYMSLEPGVMGDDAHDYEWVKA-------------</sequence>
              </node>
              <node>
              <name>N1108</name>
              <user_name>N1108</user_name>
              <dist_to_parent>0.173021</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.153393</creation_cost>
              <subtree_weight>1.12834</subtree_weight>
              <consensus>------------------------MalLNrtDWYDlARTTNcsPeirhedelfpaelegrfDIPMEKWEaYDEPYKQTYPEYVkVQREKDaGaYSVKAALERSkifEkADPGWkSVlKlHfGAIplaEYAAafaeaRleRcakapGcaNMATlGSlDEIRHaQiQLYFPHEHVSKDRQFDWAaKAfdTNEWAAIAaRHFFDDIMMaRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDfTFaSLISSIQTDESRHAQIGGPaLQIfIENGqKaEAQKKVDIAFWRAWRLFSiLTGPiMDYYTPLEHRkQSFKEFMnEWIVeQFERaihDLGLDKPWYWDiFLeQLDQQHHGMHLGVWfWRPTVWWNPaAGVTPaERDWLEEKYPGWNdTWGhCWDVIIdNLVdGntalTlPETLPIVCNMcnLPI----NYTPGdaWaVkDYqLEYNGRLYHFGSEPDRWcFEQEPERYAGHMsLVDRFLAGLIQPMDLGGALaYMDLAPGEiGDDAHgYaWVEV-------------</consensus>
              <children>
                <node>
                <name>UniRef100_O07068</name>
                <user_name>UniRef100_O07068</user_name>
                <dist_to_parent>0.153393</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>------------------------MVLLNSVDWYDLARTTNCSPEIRHRKRTISASVERRVDIPMEKWEGYDEPYKQTYPEYVRVQREKDSGAYSVKAALERSQIYEKADPGWKSVMKQHYGAISLAEY-AAFQRLRLERCARLQGCANMATMGSLDEIRHGQIQLYFPHEHVSKDRQFDWAAKAYHTNEWAAIAARHFFDDIMMTRDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDHTFASLISSIQTDESRHAQIGGPALQIFIENGQKAEAQKKVDIAFWRAWRLFSILTGPVMDYYTPLEHRKQSFKEFMNEWIVVQFERALTDLGLDKPWYWDTFLQQLDQQHHGMHLGVWFWRPTVWWNPAAGVTPAERDWLEEKYPGWNSTWGQCWDVIIENLVDGNVAQTYPETLPIVCNMSQLPI----NYTPGDAWAVKDYQLEYNGRLYHFGSEPDRWCFEQEPERYAGHMSLVDRFLAGLIQPMDLGGALKYMDLAPGEIGDDAHNYAWVE--------------</sequence>
                </node>
                <node>
                <name>UniRef100_P95408</name>
                <user_name>UniRef100_P95408</user_name>
                <dist_to_parent>0.153393</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0</creation_cost>
                <subtree_weight>1</subtree_weight>
                <sequence>------------------------MAVLNRTDWYDVARTTNWTPKYVTEDELFPPELSGSFDIPMEKWEAYDEPYKQTYPEYVKVQREKDAGVYSVKAALERSKMFENADPGWQSVLKLHFGAIPSGEYAASTAEARMMRFSKAPGMRNMATLGSMDEIRHAQLQLYFPHEHVSKDRQFDWAHKAFDTNEWAAIASRHFFDDIMMARDAISVGIMLTFGFETGFTNMQFLGLAADAAEAGDFTFSSLISSIQTDESRHAQIGGPTLQILIENGRKEEAQKKVDIAFWRAWRLFSVLTGPIMDYYTPLEHRNQSFKEFMQEWIVEQFERSIHDLGLDKPWYWDIFLEQLDQQHHGMHLGVWYWRPTVWWNPTAGVTPEERDWLEEKYPGWNDTWGHCWDVIIDNLVEGRTELTLPETLPIVCNMCNLPI----NYTPGNGWNVQDYSLEYNGRLYHFGSEPDRWIFEQEPERYAGHMTLVDRFLAGLIQPMDLGGALAYMDLAPGESGDDAHGYSWVEV-------------</sequence>
                </node>
              </children>
              </node>
            </children>
            </node>
          </children>
          </node>
        </children>
        </node>
        <node>
        <name>N1135</name>
        <user_name>N1135</user_name>
        <dist_to_parent>0.242367</dist_to_parent>
        <is_subfamily>0</is_subfamily>
        <creation_cost>0.254483</creation_cost>
        <subtree_weight>1.11735</subtree_weight>
        <consensus>MRRGSVAGPGGFGPRPWGNTKEASMPKLaRrDwYDlARDmNWaFgYVSEddVFPEELSgsfgihaEeWlaWDEPYKiTYREYVHNQagKDdgiYSiknaIARSaLfdkLDaGWKSaIkAHYGAIpmPEYfASIGEARMaRFGRAAAWRNmAaFGTLDEcRHGQaQafFPYcLiGKdPqaDWAhKAfHTNdWgViAaRqLFDDMFtANDAlSiAiQLTFTfETGFTNLQFLGMAaDAihVGDiEFGaLISSIQTDEARHaQQGEPTiKIlaegGhKaeaQfLiDhMFWRSWklFALLTGiSMDYYTPLEhRTMSFKEFiedWickQFmDQFkDfGlevPWYWEeFlnELdWvHHAiHlGVWfWRPTVWWNPDAGVSAaERdWLEeKYPGWNdrFGKlWDaIGdNiRaGkiEaTfPaTLPiVCNcChiPIcraaGVEAGALagaAPlihTHgGRdllFCcEpCeWifarqPERfagHlSlVDRFLAGeIqPPdLeGaLaYMGisPaeaGnDAqGYAWagAaaaaATGARAARR</consensus>
        <children>
          <node>
          <name>N1141</name>
          <user_name>N1141</user_name>
          <dist_to_parent>0.254483</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>------------------------MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICSPS-------IGQAPRITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASRLAA--------</consensus>
          <children>
            <node>
            <name>UniRef100_A5ECB8</name>
            <user_name>UniRef100_A5ECB8</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>------------------------MPKLQRRDYYDTARDMNWAFSYVSEDEVFPEELSKSFGIHGEEWWGWDEPYKLTYREYVHNQAGKDDGIYSIRSTIARSNLYDNLDAGWKSAIKAHYGAIPVPEYFASIGEARMARFGRAAAWRNMAAFGTLDECRHGQAQIYFPYCLLGKDPQFDWAHKAMHTNEWGVIAARSLFDDMFTANDAVSTAIQLTFTFETGFTNLQFLGMASDALHVGDIEFGALISSIQTDEARHSQQGEPTLKIMINNGKKAEAQKLVDQMFWRSWKLFALLTGISMDYYTPLESRTMSFKEFMQDWICRQFMDQFKDLGMNVPWYWEKFLPELDWVHHAYHMGVWFWRPTVWWNPDAGVSAAERDWLEQKYPGWNDRFGKLWDVIGNNVRTGQIEKTYPATLPIVCNCCHIPICSPS-------IGQAPRITTHNGRKLNFCCEVCEWVWKSQPERYETHLSVVDRFLAGHIQPPTLEGALQYMGITPDVAGNDAQGYAWDGASRLAA--------</sequence>
            </node>
          </children>
          </node>
          <node>
          <name>N1142</name>
          <user_name>N1142</user_name>
          <dist_to_parent>0.254483</dist_to_parent>
          <is_subfamily>1</is_subfamily>
          <creation_cost>0</creation_cost>
          <subtree_weight>1</subtree_weight>
          <consensus>MRRGSVAGPGGFGPRPWGNTKEASMPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGVEAGALASAAPLRHTHGGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQAAAAGATGARAARR</consensus>
          <children>
            <node>
            <name>UniRef100_Q2JGJ2</name>
            <user_name>UniRef100_Q2JGJ2</user_name>
            <dist_to_parent>0</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0</creation_cost>
            <subtree_weight>1</subtree_weight>
            <sequence>MRRGSVAGPGGFGPRPWGNTKEASMPKLARSDWYDLARDTNWSFGYVSEQDVFPEELSGTGRVPAEGWLAWDEPYKITYREYVHNQVTKDTTTYSVKNAIARSALFEKLDPGWKSVILAHYGAITMPEYLASIGEARMGRFGRAAAWRNTATFGTLDEVRHGQIQAFFPYGLIGKEPRADWALKAFHTNDWIVLAVRQLFDDMFVANDALSIALQLTFTLETGFTNLQFLGMAADAIKVGDLEFGSLISSIQTDEARHAQQGEPTIKILAEGGHKDWGQFLIDHMFWRSWRVFALLTGLSMDYYTPLEHRTMSFKEFIEEWVIKQFSDQFRDFGLEYPWYWEEFVNELTWYHHAIHLGVWNWRPTVWWNPDAGVSADERVWLEEKYPGWNRTFGKYWDAIGDNIRAGKVEATFPETLPLVCNLCQLPIVRAAGVEAGALASAAPLRHTHGGRDYLFCSEPCKWIFARRPERFAGHRSLVDRFLAGEISPPDLGGVLAYMGLSPAEQGQDATGYAWAQAAAAGATGARAARR</sequence>
            </node>
          </children>
          </node>
        </children>
        </node>
      </children>
      </node>
    </children>
    </node>
    <node>
    <name>N1139</name>
    <user_name>N1139</user_name>
    <dist_to_parent>0.90579</dist_to_parent>
    <is_subfamily>0</is_subfamily>
    <creation_cost>0.309561</creation_cost>
    <subtree_weight>3</subtree_weight>
    <consensus>-------------SNnAaDTptakKKLGLKeRYaaMTRDLgWETTYQpMDkVFPeEYDrFEGIKIHDWDKWEDPFRLTMDAYWKYQaEKEKKLYAIIDAFAQNNqLnVtDARYvNALKLFLTGVTPLEYqAHRGFAHVGRqFrGaGARVACQMQSIDELRHaQTQAiHAmSHYNKyFNGfHdfnHMHDRVWYLSVPKSFFEDArSAGGPFEFLTAISFSFEYVLTNLLFVPFMSGAAYNGDMATVTFGFSAQSDESRHMTLGLEVIKFlLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLP--KRVMSWkEAWEmYFEQNGGALFKDYGIRmPKywevAceeKDHISHQAWstFYNYgaAAaFHTWvPitedEMdWLSEKYPDFDkyYRPRyepwrEqaqaGkGERFYNkTLPMLCQTCQIPMlFTeFTEPgDPTkIcyRESdYeGeKYHFCSDGCKDIFDhEPEKYVQAWLPVHQIYQGNCGGpDLeaVLdYYhinpGrDNlDFeGSEDQKNFAAWRGqApaaed</consensus>
    <children>
      <node>
      <name>N1134</name>
      <user_name>N1134</user_name>
      <dist_to_parent>0.309561</dist_to_parent>
      <is_subfamily>0</is_subfamily>
      <creation_cost>0.245881</creation_cost>
      <subtree_weight>3</subtree_weight>
      <consensus>-------------SNnAaDTptlKKKLGLKERYAaMTRGLGWETTYQPMDKVFPQdYDkYEGIKIHDWDKWEDPFRLTMDAYWKYQGEKEKKLYAVIDAFaQNNqLgVTDARYINALKLFLTGVTPLEYaAHRGFAHvGRhFrGaGARVACQMQSIDELRHaQTQTtHaiShYNKYFNGFHdsnHMhDRVWYLSVPKSFFEDAmSAGaPFEFlTAISFSFEYVLTNLLFVPFMSGAAYNGDMaTVTFGFSAQSDESRHMTLGLEvIKFmLEQDPDNIVQrWIDKWFWRGYRLLTLVSAMMMDYMLP--KRVMSWkEAWEMYFEQNGGALFKDYGIRmPKgweqAceeKDHISHQAWsTFYNYnAAAaFHTWVPaseDEMaWLSeKYPDFDkyYRPRfEyWrEQqqAGkGeRFYNkTLPMLCQTCQIPMlFTaFTEPGDPTKICYRESdYlGnKYHFCSDGCKdIFDhEPEKYVQAWLPVHQIYQGNCGfpdLaAVLdYYhlnvGRDNlDFEGSEDQKNFAAWRGQAtkgek</consensus>
      <children>
        <node>
        <name>N1105</name>
        <user_name>N1105</user_name>
        <dist_to_parent>0.245881</dist_to_parent>
        <is_subfamily>1</is_subfamily>
        <creation_cost>0.127413</creation_cost>
        <subtree_weight>2.05465</subtree_weight>
        <consensus>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYyAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTETTHAmSTYNKFFNGfHHSNHWFDRVWYLSVPKSFFEDAySaGAPFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFKDYGIREPKGWqDACEGKDHISHQAWsTFYgFNAAAaFHTWVPStEdEMAWLSAKYPDFDRYYRPRFEYWgEQAkAGNGNRFYmKTLPMLCQTCQIPMLFT---EPGDPTKIcARESDYLGNKFHFCSDHCKEIFDHEPEKYVQAWLPVHQIYQGNCFpPDLAAVLDYYEVnmGRDNlDFEGSEDQKNFAAWRGQApqGek</consensus>
        <children>
          <node>
          <name>N1081</name>
          <user_name>N1081</user_name>
          <dist_to_parent>0.127413</dist_to_parent>
          <is_subfamily>0</is_subfamily>
          <creation_cost>0.106987</creation_cost>
          <subtree_weight>2.02565</subtree_weight>
          <consensus>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYyAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTETTHAmSTYNKFFNGfHHSNHWFDRVWYLSVPKSFFEDAYSaGAPFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFKDYGIREPKGWqDACEGKDHISHQAWsTFYgFNAAAaFHTWVPStEDEMAWLSAKYPDFDRYYRPRFEYWgEQAkAGNGNRFYmKTLPMLCQTCQIPMLFT---EPGDPTKIcARESDYLGNKFHFCSDHCKEIFDHEPEKYVQAWLPVHQIYQGNCFpPDLAAVLDYYEVnmGRDNlDFEGSEDQKNFAAWRGQApqGEk</consensus>
          <children>
            <node>
            <name>N990</name>
            <user_name>N990</user_name>
            <dist_to_parent>0.106987</dist_to_parent>
            <is_subfamily>0</is_subfamily>
            <creation_cost>0.0562231</creation_cost>
            <subtree_weight>1.47715</subtree_weight>
            <consensus>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYLAHRGFAHVGRHFTGEGARIACQMQSIDELRHYQTETTHAMSTYNKFFNGFHHSNHWFDRVWYLSVPKSFFEDAYSaG-PFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFKDYGIREPKGWQDACEGKDHISHQAWSTFYGFNAASAFHTWVP-tEDEMAWLSAKYPDFDRYYRPRFDYWGEQAKAGNGERFYMKTLPMLCQTCQIPMLFT---EPGNPTKIGARESDYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIYQGNCFPPDLAAVLDYYEVqMGRDNLDFDGSEDQKNFAAWRGQAQ----</consensus>
            <children>
              <node>
              <name>N957</name>
              <user_name>N957</user_name>
              <dist_to_parent>0.0562231</dist_to_parent>
              <is_subfamily>0</is_subfamily>
              <creation_cost>0.0424347</creation_cost>
              <subtree_weight>1.42454</subtree_weight>
              <consensus>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYLAHRGFAHVGRHFTGEGARIACQMQSIDELRHYQTE-THAMSTYNKFFNGFHHSNHWFDRVWYLSVPKSFFEDAYSSG-PFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFLLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFKDYGIREPKGWQDACEGKDHISHQAWSTFYGFNAASAFHTWVP-TEDEMAWLSAKYPDFDRYYRPRFDYWGEQAKAGN--RFYMKTLPMLCQTCQIPMLFT---EPGNPTKIGARESdYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIYQGNCFPPDLAAVLDYYEVqMGRDNLDFDGSEDQKNFAAWRGQA-----</consensus>
              <children>
                <node>
                <name>N894</name>
                <user_name>N894</user_name>
                <dist_to_parent>0.0424347</dist_to_parent>
                <is_subfamily>0</is_subfamily>
                <creation_cost>0.0208157</creation_cost>
                <subtree_weight>1.41087</subtree_weight>
                <consensus>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIKIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYLAHRGFAHVGRHFTGEGARIACQMQSIDELRHYQTE-THAMSTYNKFFNGFHHSNHWFDRVWYLSVPKSFFEDAYSSG-PFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFLLEQDPDNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFKDYGIREPKGWQDACEGKDHISHQAWSTFYGFNAASAFHTWVP-TEDEMAWLSAKYPDFDRYYRPRFDYWGEQAKAGN--RFYMKTLPMLCQTCQIPMLFT---EPGNPTKIGARESdYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIHQGNCFPPDLAAVLDYYEVqMGRDNLDFDGSEDQKNFAAWRGQA-----</consensus>
                <children>
                  <node>
                  <name>UniRef100_A0A3N8L7T2</name>
                  <user_name>UniRef100_A0A3N8L7T2</user_name>
                  <dist_to_parent>0.0208157</dist_to_parent>
                  <is_subfamily>0</is_subfamily>
                  <creation_cost>0</creation_cost>
                  <subtree_weight>1</subtree_weight>
                  <sequence>------------------DTPTLKKKLGLKDRYAAMTRGLGWETTYQPMDKVFP--YDRYEGIRIHDWDKWVDPFRLTMDAYWKYQGEKEKKLYAVIDAFTQNNFLGVTDARYINALKLFIQGVTPLEYLAHRGFAHVGRHFTGEGARVACQMQSIDELRHYQTE-THAMSTYNKFFNGFHHSNHWFDRVWYLSVPKSFFEDAYSSG-PFEFLTAVSFSFEYVLTNLLFVPFMSGAAYNGDMSTVTFGFSAQSDESRHMTLGIECIKFMLEQDPGNIVQRWIDKWFWRGYRLLTLV-AMMMDYMQP--KRVMSWRESWEMYAEQNGGALFRDYGIREPKGWQDACEGKDHISHQAWSTFYGFNAASAFHTWVP-TGDEMAWLAAKYPDFDRYYRPRFEHWGEQAQAGN--RFYMKTLPMLCQTCQIPMLFT---EPGNPTKIGARESSYLGNKFHFCSDHCKEIFDHEPQKYVQAWLPVHQIYQGNCFRPDLAAVLNYYEVGMGRDNLDFEGSEDQKNFAAWRGQA-----</sequence>
                  </node>
                  <node>
                  <name>N885</name>
                  <user_name>N885</user_name>
                  <dist_to_parent>0.0208157</dist_to_parent>
                  <is_subfamily>0</is_subfamily>
                  <creation_cost>0.0195105</creation_cost>
                  <subtree_weight>1.40765</subtree_weight>